### ISSUE TITLE
Ability to define some G-Code to execute after abort.

### ISSUE THREAD

**Issue by glowtape** [Smoothieware/Smoothieware#1006]
It would be nice if there'd be an option to specify some G-Code snippet, that gets executed after aborting a print. Pretty much what "after_suspend_gcode" does. Like this someone can chose what the printer should do after an abort, like turn off heaters and home X and Y, or whatever else.

Maybe I'll even give it a try myself to implement it, should I get a build environment up and working the next few days.

**Comment by wolfmanjm** [comment]
This is simply not am option. HALT is HALT, there is a reason for it. It also usually shuts down the power as well if properly configured, so there would be no way to execute anything after a HALT event.

If you mean abort as in aborting an sdcard print, then again it is not likely you could do much after wards other than home as the position is most likely lost. In this case abort is a manual operation and it does not seem particularly useful to execute anything after it, as yo can simply issue a Home manually. 
In pronterface you could define a button to issue an abort followed by a home, but given you have no idea where the head is in relation to the print issuing a home blindly would most likely knock the print off, or damage something.
