### ISSUE TITLE
Ability to build Smoothieware for other LPC17xx MicroControllers?

### ISSUE THREAD

**Issue by raykholo** [Smoothieware/Smoothieware#1054]
Anyone have an idea regarding what it would take to build Smoothieware for other ICs in the same range?

For example, the LPC1788FBD208,551 is also in the 17xx range, seems to have all the main peripherals of the current 1769, more memory, but I'm primarily interested in the extra GPIO pins.  

Would appreciate any thoughts/ a push in the right direction.

Thanks,
Ray

**Comment by wolfmanjm** [comment]
This is not an issue and is not the correct place to ask a question like this.

your issue does not conform to the rules :
[How to file an issue](https://github.com/Smoothieware/Smoothieware/blob/edge/ISSUE_TEMPLATE.md)

You should try a support forum on IRC or the google groups.
