### ISSUE TITLE
Limit switches enabled, but not working

### ISSUE THREAD

**Issue by hammy7867** [Smoothieware/Smoothieware#1061]
### What should I include in a bug report?

Always use the following template (you can remove what's within `[...]`, that's
only provided here as some additional information for you), **even if only adding a
"me too" to an existing ticket**:

#### What were you doing?

    I have my end stops enabled, and the my axes are homing just fine. I also have the limit switches enabled that are supposed to halt all action if any single one of them is pressed, but when I execute code and manually press my limit switches, the print just continues. 

#### What did you expect to happen?

   I expected that pressing the limit switch would halt execution of my print.
#### Branch & Commit or Version of Smoothieware

Build version: edge-3332442, Build date: Apr 22 2016 15:52:55, MCU: LPC1769, System Clock: 120MHz

#### Hardware model you are using (Make, and version)

    smoothie board 3X

#### Host and Operating System running the Host

    Pronterface, Mac OS

#### Link to and console logs

   Not sure what is required here.
    
## Endstops
endstops_enable                              true             # the endstop module is enabled by default and can be disabled here
#corexy_homing                               false            # set to true if homing on a hbot or corexy
alpha_min_endstop                            1.24^            # add a ! to invert if endstop is NO connected to ground
alpha_max_endstop                            1.25^            # NOTE set to nc if this is not installed
alpha_homing_direction                       home_to_min      # or set to home_to_max and set alpha_max
alpha_min                                    0                # this gets loaded after homing when home_to_min is set
alpha_max                                    300              # this gets loaded after homing when home_to_max is set
beta_min_endstop                             1.26^            #
beta_max_endstop                             1.27^            #
beta_homing_direction                        home_to_min      #
beta_min                                     0                #
beta_max                                     200              #
gamma_min_endstop                            1.28^            #
gamma_max_endstop                            1.29^            #
gamma_homing_direction                       home_to_min      #
gamma_min                                    0                #
gamma_max                                    200              #

alpha_max_travel                             500              # max travel in mm for alpha/X axis when homing
beta_max_travel                              500              # max travel in mm for beta/Y axis when homing
gamma_max_travel                             500              # max travel in mm for gamma/Z axis when homing

# optional order in which axis will home, default is they all home at the same time,
# if this is set it will force each axis to home one at a time in the specified order
#homing_order                                 XYZ              # x axis followed by y then z last
#move_to_origin_after_home                    false            # move XY to 0,0 after homing

# optional enable limit switches, actions will stop if any enabled limit switch is triggered
#alpha_limit_enable                          true            # set to true to enable X min and max limit switches
#beta_limit_enable                           true            # set to true to enable Y min and max limit switches
#gamma_limit_enable                          true            # set to true to enable Z min and max limit switches

alpha_fast_homing_rate_mm_s                  15               # feedrates in mm/second
beta_fast_homing_rate_mm_s                   15               # "
gamma_fast_homing_rate_mm_s                  8                # "
alpha_slow_homing_rate_mm_s                  8                # "
beta_slow_homing_rate_mm_s                   8                # "
gamma_slow_homing_rate_mm_s                  4                # "

alpha_homing_retract_mm                      5                # distance in mm
beta_homing_retract_mm                       5                # "
gamma_homing_retract_mm                      1                # "

#endstop_debounce_count                       100              # uncomment if you get noise on your endstops, default is 100

**Comment by wolfmanjm** [comment]
You have lijits commented out... try uncommenting the following lines and it will work..

```
#alpha_limit_enable true # set to true to enable X min and max limit switches
#beta_limit_enable true # set to true to enable Y min and max limit switches
#gamma_limit_enable true # set to true to enable Z min and max limit switches
```

Hint the # at the start of a line is a comment and means the line is ignored. 
For more help I recommend you read the documentation on the wiki.
