### ISSUE TITLE
Spindle does not turn off when ALARM occurs

### ISSUE THREAD

**Issue by arthurwolf** [Smoothieware/Smoothieware#1069]
#### What were you doing?

Using the spindle module to control a VFD via Gcode

#### What did you expect to happen?

ALARM occured and I expected the spindle to stop. I killed a 50 euro probe not realizing it was still on when starting the job again :)

#### Branch & Commit or Version of Smoothieware

Any recent edge version

( this is mostly a note to myself, I hope to have time to fix this soon )

**Comment by wolfmanjm** [comment]
fixed by #1236
