### ISSUE TITLE
Delta grid compensation

### ISSUE THREAD

**Issue by kenoro** [Smoothieware/Smoothieware#1075]
Firmaware version:

SENDING:version
Build version: edge-d792543, Build date: Dec 15 2016 13:37:18, MCU: LPC1769, System Clock: 120MHz
5 axis

Made the modifications to the config to save after the probing is finished but still doesnt save/ load the full grid.

> Delta Grid Probe...
Probe start ht is 34.885002 mm, probe radius is 75.000000 mm, grid size is 11x11
probe at 0,0 is 0.007501 mm
DEBUG: X75.0000, Y-75.0000, Z0.0850
DEBUG: X60.0000, Y-75.0000, Z0.0675
DEBUG: X45.0000, Y-75.0000, Z0.0975
DEBUG: X30.0000, Y-75.0000, Z0.0700
DEBUG: X15.0000, Y-75.0000, Z0.0625
DEBUG: X0.0000, Y-75.0000, Z0.0825
DEBUG: X-15.0000, Y-75.0000, Z0.0775
DEBUG: X-30.0000, Y-75.0000, Z0.0775
DEBUG: X-45.0000, Y-75.0000, Z0.1025
DEBUG: X-60.0000, Y-75.0000, Z0.0725
DEBUG: X-75.0000, Y-75.0000, Z0.0875
DEBUG: X-75.0000, Y-60.0000, Z0.0325
DEBUG: X-60.0000, Y-60.0000, Z0.0300
DEBUG: X-45.0000, Y-60.0000, Z0.0525
DEBUG: X-30.0000, Y-60.0000, Z0.0400
DEBUG: X-15.0000, Y-60.0000, Z0.0325
DEBUG: X0.0000, Y-60.0000, Z0.0450
DEBUG: X15.0000, Y-60.0000, Z0.0300
DEBUG: X30.0000, Y-60.0000, Z0.0350
DEBUG: X45.0000, Y-60.0000, Z0.0600
DEBUG: X60.0000, Y-60.0000, Z0.0400
DEBUG: X75.0000, Y-60.0000, Z0.0725
DEBUG: X75.0000, Y-45.0000, Z0.0525
DEBUG: X60.0000, Y-45.0000, Z0.0300
DEBUG: X45.0000, Y-45.0000, Z0.0450
DEBUG: X30.0000, Y-45.0000, Z0.0150
DEBUG: X15.0000, Y-45.0000, Z0.0175
DEBUG: X0.0000, Y-45.0000, Z0.0275
DEBUG: X-15.0000, Y-45.0000, Z0.0125
DEBUG: X-30.0000, Y-45.0000, Z0.0275
DEBUG: X-45.0000, Y-45.0000, Z0.0275
DEBUG: X-60.0000, Y-45.0000, Z0.0075
DEBUG: X-75.0000, Y-45.0000, Z0.0125
DEBUG: X-75.0000, Y-30.0000, Z0.0275
DEBUG: X-60.0000, Y-30.0000, Z0.0125
DEBUG: X-45.0000, Y-30.0000, Z0.0425
DEBUG: X-30.0000, Y-30.0000, Z0.0275
DEBUG: X-15.0000, Y-30.0000, Z0.0175
DEBUG: X0.0000, Y-30.0000, Z0.0325
DEBUG: X15.0000, Y-30.0000, Z0.0250
DEBUG: X30.0000, Y-30.0000, Z0.0175
DEBUG: X45.0000, Y-30.0000, Z0.0425
DEBUG: X60.0000, Y-30.0000, Z0.0275
DEBUG: X75.0000, Y-30.0000, Z0.0575
DEBUG: X75.0000, Y-15.0000, Z0.0350
DEBUG: X60.0000, Y-15.0000, Z0.0075
DEBUG: X45.0000, Y-15.0000, Z0.0275
DEBUG: X30.0000, Y-15.0000, Z0.0025
DEBUG: X15.0000, Y-15.0000, Z0.0025
DEBUG: X0.0000, Y-15.0000, Z0.0075
DEBUG: X-15.0000, Y-15.0000, Z-0.0125
DEBUG: X-30.0000, Y-15.0000, Z-0.0050
DEBUG: X-45.0000, Y-15.0000, Z-0.0025
DEBUG: X-60.0000, Y-15.0000, Z-0.0275
DEBUG: X-75.0000, Y-15.0000, Z-0.0150
DEBUG: X-75.0000, Y0.0000, Z-0.0325
DEBUG: X-60.0000, Y0.0000, Z-0.0500
DEBUG: X-45.0000, Y0.0000, Z-0.0200
DEBUG: X-30.0000, Y0.0000, Z-0.0275
DEBUG: X-15.0000, Y0.0000, Z-0.0350
DEBUG: X0.0000, Y0.0000, Z-0.0125
DEBUG: X15.0000, Y0.0000, Z-0.0200
DEBUG: X30.0000, Y0.0000, Z-0.0175
DEBUG: X45.0000, Y0.0000, Z0.0075
DEBUG: X60.0000, Y0.0000, Z-0.0125
DEBUG: X75.0000, Y0.0000, Z0.0250
DEBUG: X75.0000, Y15.0000, Z0.0225
DEBUG: X60.0000, Y15.0000, Z-0.0125
DEBUG: X45.0000, Y15.0000, Z-0.0200
DEBUG: X30.0000, Y15.0000, Z-0.0375
DEBUG: X15.0000, Y15.0000, Z-0.0575
DEBUG: X0.0000, Y15.0000, Z-0.0425
DEBUG: X-15.0000, Y15.0000, Z-0.0700
DEBUG: X-30.0000, Y15.0000, Z-0.0650
DEBUG: X-45.0000, Y15.0000, Z-0.0650
DEBUG: X-60.0000, Y15.0000, Z-0.0900
DEBUG: X-75.0000, Y15.0000, Z-0.0750
DEBUG: X-75.0000, Y30.0000, Z-0.1050
DEBUG: X-60.0000, Y30.0000, Z-0.1125
DEBUG: X-45.0000, Y30.0000, Z-0.0900
DEBUG: X-30.0000, Y30.0000, Z-0.1000
DEBUG: X-15.0000, Y30.0000, Z-0.1000
DEBUG: X0.0000, Y30.0000, Z-0.0750
DEBUG: X15.0000, Y30.0000, Z-0.0950
DEBUG: X30.0000, Y30.0000, Z-0.0675
DEBUG: X45.0000, Y30.0000, Z-0.0375
DEBUG: X60.0000, Y30.0000, Z-0.0450
DEBUG: X75.0000, Y30.0000, Z-0.0075
DEBUG: X75.0000, Y45.0000, Z-0.0475
DEBUG: X60.0000, Y45.0000, Z-0.0875
DEBUG: X45.0000, Y45.0000, Z-0.1000
DEBUG: X30.0000, Y45.0000, Z-0.1200
DEBUG: X15.0000, Y45.0000, Z-0.1225
DEBUG: X0.0000, Y45.0000, Z-0.1300
DEBUG: X-15.0000, Y45.0000, Z-0.1425
DEBUG: X-30.0000, Y45.0000, Z-0.1375
DEBUG: X-45.0000, Y45.0000, Z-0.1450
DEBUG: X-60.0000, Y45.0000, Z-0.1500
DEBUG: X-75.0000, Y45.0000, Z-0.1550
DEBUG: X-75.0000, Y60.0000, Z-0.1600
DEBUG: X-60.0000, Y60.0000, Z-0.1650
DEBUG: X-45.0000, Y60.0000, Z-0.1500
DEBUG: X-30.0000, Y60.0000, Z-0.1550
DEBUG: X-15.0000, Y60.0000, Z-0.1550
DEBUG: X0.0000, Y60.0000, Z-0.1350
DEBUG: X15.0000, Y60.0000, Z-0.1425
DEBUG: X30.0000, Y60.0000, Z-0.1175
DEBUG: X45.0000, Y60.0000, Z-0.1050
DEBUG: X60.0000, Y60.0000, Z-0.0975
DEBUG: X75.0000, Y60.0000, Z-0.0550
DEBUG: X75.0000, Y75.0000, Z-0.0800
DEBUG: X60.0000, Y75.0000, Z-0.1450
DEBUG: X45.0000, Y75.0000, Z-0.1425
DEBUG: X30.0000, Y75.0000, Z-0.1625
DEBUG: X15.0000, Y75.0000, Z-0.1825
DEBUG: X0.0000, Y75.0000, Z-0.1725
DEBUG: X-15.0000, Y75.0000, Z-0.1875
DEBUG: X-30.0000, Y75.0000, Z-0.1925
DEBUG: X-45.0000, Y75.0000, Z-0.1900
DEBUG: X-60.0000, Y75.0000, Z-0.2100
DEBUG: X-75.0000, Y75.0000, Z-0.2050
 0.0875  0.0725  0.1025  0.0775  0.0775  0.0825  0.0625  0.0700  0.0975  0.0675  0.0850
 0.0325  0.0300  0.0525  0.0400  0.0325  0.0450  0.0300  0.0350  0.0600  0.0400  0.0725
 0.0125  0.0275  0.0175  0.0150  0.0450  0.0300  0.0525
 0.0275  0.0125  0.0425  0.0275  0.0175  0.0325  0.0250  0.0175  0.0425  0.0275  0.0575
 0.0075  0.0350
-0.0325 -0.0500 -0.0200 -0.0275 -0.0350 -0.0125 -0.0200 -0.0175  0.0075 -0.0125  0.0250
-0.0750 -0.0900 -0.0650 -0.0650 -0.0700 -0.0425 -0.0575 -0.0375 -0.0200 -0.0125  0.0225
-0.0900 -0.1000 -0.1000 -0.0750 -0.0950 -0.0675 -0.0375 -0.0450 -0.0075
-0.1550 -0.1500 -0.1450 -0.1375 -0.1425 -0.1300 -0.1225 -0.1200 -0.1000 -0.0875 -0.0475
-0.1175 -0.1050 -0.0975 -0.0550
-0.2050 -0.2100 -0.1900 -0.1925 -0.1875 -0.1725 -0.1825 -0.1625 -0.1425 -0.1450 -0.0800
Probe completed

After that I send 

> >>> m375.1
SENDING:M375.1
 0.0875  0.0725  0.1025  0.0775  0.0775  0.0825  0.0625  0.0700  0.0975  0.0675  0.0850
 0.0325  0.0300  0.0525  0.0400  0.0325  0.0450  0.0300  0.0350  0.0600  0.0400  0.0725
 0.0275  0.0175  0.0150  0.0450  0.0300  0.0525
 0.0275  0.0125  0.0425  0.0275  0.0175  0.0325  0.0250  0.0175  0.0425  0.0275  0.0575
-0.0150 -0.0275 -0.0025 -0.0050 -0.0125  0.0075  0.0025  0.0025  0.0275  0.0075  0.0350
-0.0325 -0.0500 -0.0200 -0.0275 -0.0350 -0.0125 -0.0200 -0.0175  0.0075 -0.0125  0.0250
-0.0750 -0.0900 -0.0650 -0.0650 -0.0700 -0.0425 -0.0575 -0.0375 -0.0200 -0.0125  0.0225
-0.1000 -0.1000 -0.0750 -0.0950 -0.0675 -0.0375 -0.0450 -0.0075
-0.1550 -0.1500 -0.1450 -0.1375 -0.1425 -0.1300 -0.1225 -0.1200 -0.1000 -0.0875 -0.0475
-0.1050 -0.0975 -0.0550
-0.2050 -0.2100 -0.1900 -0.1925 -0.1875 -0.1725 -0.1825 -0.1625 -0.1425 -0.1450 -0.0800

I attach also the grid file maybe you can view it. Is it possible that the values are there and available but for some god known reason are not displayed? 
[delta.zip](https://github.com/Smoothieware/Smoothieware/files/656640/delta.zip)

**Comment by wolfmanjm** [comment]
I said to reopen the other one
