### ISSUE TITLE
Overextrusion when printing 20x20cm cube after new motion control updates.

### ISSUE THREAD

**Issue by dreamscape74** [Smoothieware/Smoothieware#1098]
#### What were you doing?
Upgrade to latest edge Firmware
Trying to print 20x20 calibration box (see attached gcode)

#### What did you expect to happen?

All layers aligned and extrusion perfect.
Function similar to previous firmware

#### What happened instead?

The start of every layer over extruded.

#### Branch & Commit or Version of Smoothieware

Old Firmware (has no over extrusion)
Build version: edge-861f44a, 
Build date: Jun 10 2016 13:49:32, 
MCU: LPC1769, System Clock: 120MHz

New Fimrware (Has over extrusion)
Build version: edge-75df940, 
Build date: Jan 18 2017 20:23:52, 
MCU: LPC1769, System Clock: 120MHz
5 axis

#### Hardware model you are using (Make, and version)

Beast 3D Printer with external stepper drivers 
Smoothieboard 5XC 1b

#### Host and Operating System running the Host
Windows 10
Tested with both USB connection and SD card print through web interface.

Sliced with Simplify3d
Sliced Gcode
[20mm-box.txt](https://github.com/Smoothieware/Smoothieware/files/719470/20mm-box.txt)

#### Link to and console logs

Unable to retrieve entire log.
    
#### Link to running config and M503 results
[M503.txt](https://github.com/Smoothieware/Smoothieware/files/719570/M503.txt)
[config.txt](https://github.com/Smoothieware/Smoothieware/files/719468/config.txt)

**Comment by wolfmanjm** [comment]
Did you reverse the e motors as required in the upgrade notes? (Did you read the upgrade notes?)
Did you try to re calibrate your extrusion with new edge?
This is NOT reproducible, and works as expected here, so I suspect something on your end but not exactly sure what it could be.
Please try to recalibrate your e steps.

One thing I noticed is your acceleration is WAY to high for an extruder, and this may not have been noticed with the old firmware. Try changing it to 500 instead of 5000

**Comment by wolfmanjm** [comment]
FYI...

G28 Y ; Home Y first
G28 X ;Then home X
G28 Z ;then home Z

Are illegal gcodes
It must be Y0 X0 Z0 this will probably die in the future even as it may work now.

**Comment by wolfmanjm** [comment]
It is probably NOT a good idea to put this in the gcode... M221 S100 it is NOT designed to be put in gcode and may well cause extrusion artifacts. Please remove them.
M221 is designed to be an override set manually for tunign extrusion, it is NOT a regular Gcode and MUST not be used as such.

**Comment by wolfmanjm** [comment]
As a rule it is not recommended to use relative extrusion. there is absolutely no need for it and it can cause issues as it is never reset.
I recommend you use absolute extrusion as the norm.
This will probably also fix your issues once you remove the M221 from you gcode generation.

**Comment by wolfmanjm** [comment]
closed due to lack of response
