### ISSUE TITLE
Error parsing config "switch.blah.input_pin_behavior momentary"

### ISSUE THREAD

**Issue by ghost** [Smoothieware/Smoothieware#1113]
#### What were you doing?

Running with a config file containing
`switch.blah.input_pin_behavior momentary`

#### What did you expect to happen?

Proper parsing of the config file.

#### What happened instead?

A crash.

In Switch::on_config_reload(), I believe this line to be in error:

`this->input_pin_behavior = THEKERNEL->config->value(switch_checksum, this->name_checksum, input_pin_behavior_checksum )->by_default(momentary_checksum)->as_number();`

The value in the config file is a string ("momentary" or "toggle"), but the default value given is a checksum (`uint16_t`) and the result is parsed `as_number()`. This takes things right off the rails as "momentary" gets pared down to the hex value "ea"! Anyway, one possible fix is this:

`std::string input_pin_behavior = THEKERNEL->config->value(switch_checksum, this->name_checksum, input_pin_behavior_checksum )->by_default("momentary")->as_string();`

`this->input_pin_behavior = (input_pin_behavior == "momentary") ? momentary_checksum : toggle_checksum;`

or you could make `this->input_pin_behavior` a `std::string`, but other code in Switch.cpp would have to change as well.

#### Branch & Commit or Version of Smoothieware

edge commit f2246c7d0ee88b4071159db7a01c95f6ac906e76

#### Hardware model you are using (Make, and version)

Smoothieboard v1.1

#### Host and Operating System running the Host

OSX Eclipse and gdb

#### Link to and console logs

n/a
    
#### Link to running config and M503 results

n/a

I have read the [Wiki](http://smoothieware.org) and Especially the [Trouble Shooting section](http://smoothieware.org/troubleshooting)... 

Copy-paste this template **completely**. Do not skip any lines!

It might happen that you are asked to provide a more thorough crash log which you can find out how to do [here](http://smoothieware.org/mri-debugging
)

**Comment by wolfmanjm** [comment]
FYI for future reference you should have edited the original issue rather than creating a new one.
Anyway I fixed this in PR #1114
