### ISSUE TITLE
DHCP fails due to discarded ethernet response frame 

### ISSUE THREAD

**Issue by reedb** [Smoothieware/Smoothieware#1119]
#### What were you doing?
Booting with:
  network.ip_address                           auto             # use dhcp to get ip address  
instead of staic IP parameters.

#### What did you expect to happen?
DHCP to discover IP parameters.

#### What happened instead?
No IP parameters assigned. 

#### Branch & Commit or Version of Smoothieware
Build version: edge-d27b9dd, Build date: Feb 10 2017 09:32:25, MCU: LPC1769, System Clock: 120MHz

#### Hardware model you are using (Make, and version)
Smoothieboard 4X

#### Host and Operating System running the Host
OSX

#### Link to and console logs

send_discover:249
WARNING: Discarded ethernet frame that is too big: C4600251, 594 - 404
(Received: 594 bytes, has room for 404 bytes)

#### End template

Fix:
In ./libs/Network/uip/uip-conf.h:
  #define UIP_CONF_BUFFER_SIZE     400
goes to:
  #define UIP_CONF_BUFFER_SIZE     600

**Comment by arthurwolf** [comment]
I believe you made a mistake somewhere, there is no content.

**Comment by reedb** [comment]
Working on that now. I just inserted the blank template apparently.

-Reed

**Comment by reedb** [comment]
Updated now. Do you want to have a short discussion on IRC? -Reed

**Comment by wolfmanjm** [comment]
I believe this is an issue with your DHCP server sending too big packets. UDP packets are not supposed to exceed 512 bytes.
Increasing this wastes memory IMO and is not an option for the general users. Memory is extremely tight in smoothie, generally increasing the UDP packets size just for one DHCP server that seems to be sending illegal packets is not an option I am afraid.

**Comment by wolfmanjm** [comment]
Also setting the UIP buffer to 600 affects all network not just UDP, and will significantly slow down TCP/IP as well, the 400 was chosen to be optimum speed without using too much memory.
I suggest you reconfigure your DHCP server to send legal sized UDP packets (perhaps turn off a few options in it). Or use static IP instead, or of course you can run your own build with UIP packets set larger but look out for out of memory crashes and slower network performance.

**Comment by reedb** [comment]
My DHCP server is a WRT160N V3. A pretty popular router. I see no options which would allow a decrease in the DCHP options size. I was looking for some field that could be set in the discover packet that might limit the size of the response. I tried using UIP_CONF_DHCP_LIGHT but that didn't help. I'll also note that 400 < 500 so there may be other UDP packets that have issues.

**Comment by wolfmanjm** [comment]
well sorry about that. However there is a fairly strict spec on UDP packet size which says < 512 byes if you want it to traverse all known routers. As we only use UDP for DHCP, and DHCP packets are generally well under 400 bytes it is not usually an issue. Maybe you have a  particularly long host name? either way 600 bytes exceeds the standard recommended length for UDP so the router is at fault here I am afraid.
So you have the options I outlined earlier. I suspect one of those will work for you.

**Comment by wolfmanjm** [comment]
I researched this a little more, and found this in RFC1533.

```
9.8. Maximum DHCP Message Size

   This option specifies the maximum length DHCP message that it is
   willing to accept.  The length is specified as an unsigned 16-bit
   integer.  A client may use the maximum DHCP message size option in
   DHCPDISCOVER or DHCPREQUEST messages, but should not use the option
   in DHCPDECLINE messages.

   The code for this option is 57, and its length is 2.  The minimum
   legal value is 576 octets.

    Code   Len     Length
   +-----+-----+-----+-----+
   |  57 |  2  |  l1 |  l2 |
   +-----+-----+-----+-----+
```

Unfortunately we cannot set the buffer size to 576, so in the event DHCP fails to work the only alternative is to use static ip addresses, I'll add this to the wiki.

FWIW it seems many DHCP servers send less than 400 bytes in the reply packets.

**Comment by reedb** [comment]
I did add a one line comment to that effect:

"Due to buffer size limitations, some DHCP servers are not supported."

Thanks, -Reed
