### ISSUE TITLE
Actions in outside workspace

### ISSUE THREAD

**Issue by userosos** [Smoothieware/Smoothieware#1126]
Firmware can drive an hot-end or hot-bed outside the workspace. It very dangerous. Can you add in to config file ban the action (Hot-end outside from workspace).

**Comment by arthurwolf** [comment]
Hey.

First off, note that you are not respecting the rules for posting issues, and that issues are for bugs, and should not be used to request features ( there are a lot of other ways to do that ).

Second : this is a feature called "soft endstops", and it is a planned feature, but it is very difficult to implement correctly, so it is taking time.

Cheers.

**Comment by userosos** [comment]
I'm sorry. I understand. How soon it do?

**Comment by arthurwolf** [comment]
It is a very big project, I do not know when it will be done, anyone who can code C++ is welcome to try to help.
There is some information here : https://docs.google.com/document/d/1U6nzx1boqF-J2GGPWF4yIaaVib0JNodVWSKBfwiyp_M/edit#heading=h.79oxultkpcgc

**Comment by userosos** [comment]
I Am an engineer. I am not know code C++ but i can think about how realize scheme on principal level. I need for this?

**Comment by arthurwolf** [comment]
At this point we already have a principal level scheme, we mostly only need the actual code to be written.
But thanks for offering.

**Comment by qharley** [comment]
I have a functional soft endstop solution running on the Morgans.
Works well.

I will give it another go with the specification in hand.   lets see

**Comment by userosos** [comment]
Very well.
