### ISSUE TITLE
Add support for more axes - i.e.: X, Y, Z, A, B, C axes

### ISSUE THREAD

**Issue by ghost** [Smoothieware/Smoothieware#120]
It would be great if Smoothie would allow for configuring the number of axes, i.e. allow for more than three axes and the axis names i.e. "XYZABC".

Don't know how much effort needs to be put in on the coding side.

A use-case would be @koppi 's six-axes Mitsubishi RM501 MoveMaster robot -- it's an oldtimer robot with a new diy servo controller unit, see here - http://www.youtube.com/watch?v=RJ7PFPT9ocw

What do you think?

**Comment by arthurwolf** [comment]
Hey.

Yep. That's kind of what we are aiming at ultimately.

Lots of work to be done before we get there though.

Cheers :)

On Wed, Nov 12, 2014 at 7:01 PM, mohag <notifications@github.com> wrote:

> Thinking about it, it would be interesting if you can map G-code variables
> to axises via the arm-solution type transforms...
>
> One way would be that each motion type takes certain configurable G-code
> axises as input and output to steppers (possibly with the option to chain
> them) (outputs can likely then also be defined as say linear / rotational
> (say with steps per degree?)...) (Different types with different endstops
> type configurations...) (Not sure if that would be necessary...)
>
> For the current robot code, they have these fundamental relationships:
>
>    - Cartesian - 1 axis in, 1 linear output
>    - Delta - 3 axis in, 3 linear outputs
>    - Morgan SCARA - 2 axis in, 2 rotary outputs
>    - H-bot - 2 axis in, 2 linear? outputs
>    - Rotatable cartesian - 3 axis in, 3 out (linear?)
>
> So to control a Morgan, you would have X and Y go through the robot code
> and output to alpha and beta and Z defined as a direct linear axis.
>
> Extruders can likely also run on top of this type of setup (possibly with
> a special output to allow for auto-retraction, etc...)
>
> This is more an idea for a future major version than an easy quick goal...
>
> So for the foam cutter, the definition would look something like this:
> (Using X and Y for one end and A and B for the other) (Settings for each
> driver keeps current setup)
>
> gcode_axis A B X Y
> linear_axis_enable 4
> linear_axis_1_input A
> linear_axis_1_ouptut gamma
> linear_axis_2_input B
> linear_axis_2_ouptut delta
> linear_axis_3_source X
> linear_axis_3_ouptut alpha
> linear_axis_4_input Y
> linear_axis_4_ouptut beta
>
> A theoretical setup for a Morgan + H-bot foam cutter would be something
> like:
>
> gcode_axis A B X Y
> h_bot_enable 1  # number of processors of type
> morgan_scara_enable 1
> h_bot_1_input_x A
> h_bot_1_input_y B
> h_bot_1_input_a gamma
> h_bot_1_input_b delta
> h_bot_1_setting_a reasonalbe_value
> morgan_scara_1_input_x X
> morgan_scara_1_input_y Y
> morgan_scara_1_output_theta alpha
> morgan_scara_1_output_psi beta
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/120#issuecomment-62762528>
> .
>



-- 
Courage et bonne humeur.

**Comment by koppi** [comment]
Hi, I did not have a look into Smoothieware's source code for the last two years. I support for six axes already there? I implemented the kinematics of my Mitsubishi Movemaster RM-501 II robot in a small program, see: https://github.com/koppi/rm501 I'd like to integrate the 5-DOF kinematics into Smoothieware.

**Comment by arthurwolf** [comment]
Hey !

On Thu, Jun 18, 2015 at 7:12 PM, Jakob Flierl <notifications@github.com>
wrote:

> Hi, I did not have a look into Smoothieware's source code for the last two
> years. I support for six axes already there?
>

No.
It's quite a bit of work to add, but if you are interrested in doing so,
I'll gladly assist you.


I implemented the kinematics of my Mitsubishi Movemaster RM-501 II robot in
> a small program, see: https://github.com/koppi/rm501 I'd like to
> integrate the 5-DOF kinematics into Smoothieware.
>

Awesome :)

Cheers.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/120#issuecomment-113224145>
> .
>



-- 
Courage et bonne humeur.

**Comment by wolfmanjm** [comment]
This is potentially fixed with PR #989

**Comment by openhardwarecoza** [comment]
Awesome awesome awesome!    Guys,  please help test! #989
