### ISSUE TITLE
Firmware display on LCD missing?

### ISSUE THREAD

**Issue by KirAsh4** [Smoothieware/Smoothieware#1207]
With the previous firmware, when I recompiled for a 4-axis system, the firmware is displayed on the LCD when it's turned on. With the latest one, after compiling I get a string that reads '>11myvar2' displayed. How/Where do I change that so it correctly displays the firmware version?

Compile platform, Win10 Pro, 64bit.
Grabbed latest github source about 30 minutes ago.

![smoothieedge-11myvar2](https://user-images.githubusercontent.com/4676811/29245735-e3d7be22-7fa0-11e7-844e-c6adece4a031.jpg)

**Comment by KirAsh4** [comment]
Looks like the git calls in 'generate-version.bat' file are failing. The machine I'm working on does have git installed, however I downloaded the source as a zip file and compiled from there. So I'm thinking it's failing due to it not being a valid git repository locally. Looking at the previous source I downloaded, it came with a .git folder, whereas this new one did not.

**Comment by wolfmanjm** [comment]
That is correct you need a real github repo that has been pulled.

**Comment by KirAsh4** [comment]
This would be a new development then. As I stated, previously when I downloaded a Zip of the source, I was able to do a custom compile (for 4 axis) and get the correct information displayed. Now it doesn't work.
