### ISSUE TITLE
Bang Bang temperature on new print bug

### ISSUE THREAD

**Issue by LucaBertuolo** [Smoothieware/Smoothieware#1216]
There is a bug in Bang Bang bed driving...
If a print is aborted and the bed is hot, in a new print the board will wait that the bed plate cool down...

Example:
- launch a print, the bed plate reaches 40°
- Abort the print
- launch a new print, the print does not start and still wait that the heat bed go down to set temperature

That's is not a problem in a small bed plate...
But in a larger plate(>300x300) well isolated, the temperature will decrease very slowly...
In my printer the bed go down from 40 to 30° in 10minutes...So i have to wait 10mins before launch a new print.... 

I can solve partially this problem with a small hysteresis, but then my bed plate go on/off too quicly...and it's a 800W bed plate....

**Comment by wolfmanjm** [comment]
That is not a bug that is just the way it works.
