### ISSUE TITLE
CNC firmware does not support temperature control while regular firmware does not support Huanyang spindle control

### ISSUE THREAD

**Issue by FrenkK** [Smoothieware/Smoothieware#1224]
I wanted to protect the air-cooled spindle on my homebrew CNC mill by adding a temperature sensor. I noticed that this is impossible, because I can either:
a) use the CNC firmware build that will enable me to use a Huanyang frequency control for my spindle but not to use the temperature control for the temperature sensor or
b) use the regular firmware that will enable me to use temperature control but not the spindle control.

The simplest way to solve this would be to just enable Huanyang spindle control in the regular firmware. I don't know if there are technical reasons why this is not already enabled and I unfortunately lack the Linux-fu to make a custom build myself ...

**Comment by wolfmanjm** [comment]
The only way is to make a custom build, it is not that hard read the wiki, you can do it on windows if you must.
