### ISSUE TITLE
A Bug in the "MorganSCARASolution.cpp"

### ISSUE THREAD

**Issue by jtuomola** [Smoothieware/Smoothieware#1229]
**Cartesian_to_actuator function gives incorrect values, if arm1_length is not equal with arm2_length**

void MorganSCARASolution::cartesian_to_actuator(const float cartesian_mm[], ActuatorCoordinates &actuator_mm ) const
{

....
    if (this->arm1_length == this->arm2_length)
        SCARA_C2 = (SQ(SCARA_pos[X_AXIS]) + SQ(SCARA_pos[Y_AXIS]) - 2.0f * SQ(this->arm1_length)) / (2.0f * SQ(this->arm1_length));
    else
**# incorrect**

        SCARA_C2 = (SQ(SCARA_pos[X_AXIS]) + SQ(SCARA_pos[Y_AXIS]) - SQ(this->arm1_length) - SQ(this->arm2_length)) / (2.0f * this->SQ(arm1_length));

**# should be instead**
`       SCARA_C2 = (SQ(SCARA_pos[X_AXIS]) + SQ(SCARA_pos[Y_AXIS]) - SQ(this->arm1_length) - SQ(this->arm2_length)) / (2.0f * this->arm1_length * this->arm2_length);`
....

**Comment by wolfmanjm** [comment]
comments @qharley ?

**Comment by qharley** [comment]
Projects interfering.  Will take a look at it in a minute.

**Comment by wolfmanjm** [comment]
As no more information has been provided I am closing this issue.
