### ISSUE TITLE
Thermal runaway detection algorithm works incorrectly

### ISSUE THREAD

**Issue by sareph** [Smoothieware/Smoothieware#1232]
#### What were you doing?

Printing. Decreasing platform temperature (after first layer) causes smoothie to trigger temperature runaway event. Change from 120 to 70. 
"Error: Temperature runaway on B (delta temp 41.844), HALT asserted, TURN POWER OFF IMMEDIATELY - reset or M999 required". 
Recorded temperature at time of halt: 113.909, target: 70.000.

#### What did you expect to happen?

That smoothie will wait for bed to cool down, and then stabilize temperature at new level.

#### What happened instead?

Smoothie triggers temperature runaway and halts everything. This happens after ~24-30 seconds after temperature was changed.

#### Branch & Commit or Version of Smoothieware

Last edge, from 13 oct.
Build version: edge-ededcd5, Build date: Oct 13 2017 13:20:17, 17, MCU: LPC1768, System Clock: 120MHz

**Comment by wolfmanjm** [comment]
This is a configuration error, you need to set  runaway_cooling_timeout as per the wiki, if you regularly lower the temp after heating up.
Please read the wiki.
