### ISSUE TITLE
M112 send PSU output pin high before communications disconnect

### ISSUE THREAD

**Issue by overling** [Smoothieware/Smoothieware#1245]
#### What were you doing?

I was sending the command M112 from octoprint

#### What did you expect to happen?
I expected the heaters to turn off and possibly the controller to halt and disconnect from octoprint

#### What happened instead?
The power supply turned on meaning it sent the PSU output pin to high generally equivalent to an M80 command.   Then it disconnected the controller from octoprint but left the power supplies turned on.  
Pin 1.22

#### Branch & Commit or Version of Smoothieware

I am not sure, I do not have pronterface.  It should be fairly new.

#### Hardware model you are using (Make, and version)

 MKS Sbase 1.3.   I realize this is not your board but on the chance the same thing happens in one of your smoothieboard I don't want someones house to burn down when the M112 command is issued.  This is the standard command sent in the emergency stop plugin in octoprint

#### Host and Operating System running the Host
raspberry pie and octoprint 1.36

#### Link to and console logs

   not sure how to do this yet.
    
#### Link to running config and M503 results
[...]
Send: N60788 M503*36
Recv: ; No config override
Recv: ;Steps per unit:
Recv: M92 X318.75601 Y318.75601 Z3210.50537
Recv: ;Acceleration mm/sec^2:
Recv: M204 S1000.00000 Z120.00000
Recv: ;X- Junction Deviation, Z- Z junction deviation, S - Minimum Planner speed mm/sec:
Recv: M205 X0.05000 Z-1.00000 S0.00000
Recv: ;Max cartesian feedrates in mm/sec:
Recv: M203 X166.66667 Y166.66667 Z8.33333
Recv: ;Max actuator feedrates in mm/sec:
Recv: M203.1 X200.00000 Y200.00000 Z2.50000
Recv: ;WCS settings
Recv: G54
Recv: ;Digipot Motor currents:
Recv: M907 X0.90000 Y0.90000 Z1.20000 A0.80000 B1.20000
Recv: ;Home offset (mm):
Recv: M206 X0.00 Y0.00 Z0.00
Recv: ;E Steps per mm:
Recv: M92 E1674.0000 P57988
Recv: ;E Filament diameter:
Recv: M200 D0.0000 P57988
Recv: ;E retract length, feedrate:
Recv: M207 S6.0000 F2700.0000 Z0.0000 Q6000.0000 P57988
Recv: ;E retract recover length, feedrate:
Recv: M208 S0.0000 F480.0000 P57988
Recv: ;E acceleration mm/sec��:
Recv: M204 E2000.0000 P57988
Recv: ;E max feed rate mm/sec:
Recv: M203 E70.0000 P57988
Recv: ;E Steps per mm:
Recv: M92 E1.0000 P39350
Recv: ;E Filament diameter:
Recv: M200 D0.0000 P39350
Recv: ;E retract length, feedrate:
Recv: M207 S3.0000 F2700.0000 Z0.0000 Q6000.0000 P39350
Recv: ;E retract recover length, feedrate:
Recv: M208 S0.0000 F480.0000 P39350
Recv: ;E acceleration mm/sec��:
Recv: M204 E1000.0000 P39350
Recv: ;E max feed rate mm/sec:
Recv: M203 E1000.0000 P39350
Recv: ;PID settings:
Recv: M301 S0 P10.0000 I0.3000 D200.0000 X255.0000 Y255
Recv: ;Max temperature setting:
Recv: M143 S0 P268.0000
Recv: ;PID settings:
Recv: M301 S3 P10.0000 I0.3000 D200.0000 X255.0000 Y255
Recv: ;Max temperature setting:
Recv: M143 S3 P120.0000
Recv: 
Recv: ok

**Comment by wolfmanjm** [comment]
This is simply a configuration error. You need to configure your PSU pin appropriately to handle or not handle a HALT condition, see the wiki.
