### ISSUE TITLE
Home any axis with move more than 500mm crashes Smootieware.

### ISSUE THREAD

**Issue by markkahler** [Smoothieware/Smoothieware#1248]
#### What were you doing?

I am building a Core-XY printer with the following print volume:
alpha_max = 745
beta_max = 510
gamma_max = 500
All basic functions seem to work when the End Effector has not exceeded 500mm in the alpha (x) or beta (y) directions.

#### What did you expect to happen?
If x or y > 500mm and G28, G28 X0 or G28 Y0 is issued, expect End Effector to move to the Home position.

#### What happened instead?
When G28 is issued, the End Effector will start to move Home for the requested axit, but then stop before reaching the endstop if the End Effector was away from Home by more than 500mm.

The following error is posted in Repetier Host: **ERROR: Homing cycle failed**

All outputs from the board are turned off.
The only way to recover is to do a complete power cycle of the board.
This issue happens when the command is issued from both Repetier Host and the Control Panel.
 
#### Branch & Commit or Version of Smoothieware
https://github.com/Smoothieware/Smoothieware/tree/edge/FirmwareBin
Latest commit 3c45dcc

#### Hardware model you are using (Make, and version)

MKS-SBASE v1.3 + MKS-TFT-3.2 v3.0

#### Host and Operating System running the Host

Repetier Host v2.0.5 running on Win7

#### Link to and console logs

None.
    
#### Link to running config and M503 results

https://pastebin.com/TMp29Yf4

I have read the [Wiki](http://smoothieware.org) and Especially the [Trouble Shooting section](http://smoothieware.org/troubleshooting)... 

Copy-paste this template **completely**. Do not skip any lines!

It might happen that you are asked to provide a more thorough crash log which you can find out how to do [here](http://smoothieware.org/mri-debugging
)

**Comment by wolfmanjm** [comment]
First as you are using an MKS sbase I suggest you ask them for support not us. They do not support the firmware development so we do not support their users.

Second you could red the wiki and discover a setting called xxx_max_travel.

This is NOT a bug it is user error, and not reading the documentation.
