### ISSUE TITLE
feature request Encoder quadrature + index for late threading and other rigid tapping

### ISSUE THREAD

**Issue by alkabal** [Smoothieware/Smoothieware#1261]
Hi all

I only write this message for speak about possibility to add spindle encoder quadrature and spindle index.

The project is for make smoothie lathe driving capabilies, and offers possibility to do threading.

I think this is a too hard job for me but if you make me in good direction, i can try to do some things, if i understand good encoder from GLCD is equivalent as a quad encoder AB, and Index is like a switch.

But interaction with step pulse and speed synchronisation i really dark for my understanding.

So do you know if this is possible ?
Have you some interest for this ?
Possible to help ?

I can understand if nobody like to work/add/help for this, in this way i have start to learn about linuxcnc but for me smoothie is my first attempt in this world and for now i really like your board, support and wiki, only this feature is missing for full use of a cnc lathe lathe. (oh no i have forgot missing tool table).

Best regards, sorry for inconvenience.

Aurelien

for reference :
http://linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G33_1-Rigid-Tapping
http://linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G76-Threading-Canned

**Comment by wolfmanjm** [comment]
This is not something we can do . sorry.

**Comment by arthurwolf** [comment]
If you find somebody ready to do this, it'd probably be best implemented as a separate module.
It'd require a few weird things that would probably make it so it'd have to be kept in a separate branch for a long while ( in particular, having it's own separate step generator that's synced to the encoder ).
It's something I want to take a crack at at some point, but it'll probably be very difficult, and the first implementations probably won't look very nice or play well with the rest of the code ...
