### ISSUE TITLE
MAX31855 cannot be used readonly

### ISSUE THREAD

**Issue by RadicalZephyr** [Smoothieware/Smoothieware#1286]
I have found that setting a thermocouple that is read with a Max31855 chip to be read only (no `heater_pin` configured), causes it not to work, that is it always reports an infinite value.

This is because the temperature control module does not register for the `ON_IDLE` event for a read only configuration, but that event is when the Max31855 module is communicated with.

I'm not sure what the appropriate way to fix this is, but it seems like something worth noting in case others run into it.  For now, I will add a note to the wiki page mentioning not to configure it without a heater pin.

**Comment by wolfmanjm** [comment]
Fixed
