### ISSUE TITLE
Smoothie-stream.py doesn't know how to handle thermal runaway error

### ISSUE THREAD

**Issue by lordofhyphens** [Smoothieware/Smoothieware#1312]
If the thermal runaway is triggered when sending with smoothie-stream, there's no indication to the controlling process and it will happily keep sending lines until the file is done.

Since we're already reading the output from smoothie, it should be possible to parse the "!!" smoothie kicks back when you try to do something that isn't a M999 and abort early with an error message to tell the user what happened. Raising an uncaught exception would kill the Python script and provide a useful exit code for any application that is calling smoothie-stream.

I have a PR ready to address this, but wanted to see if it was considered "useful"  by other people.

**Comment by wolfmanjm** [comment]
python stream is more of an example of how to stream over network, rather than to be intended to be actually used. So keeping it simple was the goal. however if you can fox it correctly without being overly verbose it would be accepted.
