### ISSUE TITLE
Second G1 command parameters are ignored if no move is detected.

### ISSUE THREAD

**Issue by FriedZombie** [Smoothieware/Smoothieware#1335]
The second G* command is ignored if the first command has an identical location.
In that case also the arguments of the first command are ignored as well. So that spindle speed / laser strength / etc... are never set.

See also: t-oster/LibLaserCut#87

**Comment by wolfmanjm** [comment]
I'm not sure if this is right or wrong. but yes it is deliberate. If there is no movement then the entire command is ignored. I will look to see if this could be fixed or not. But if grbl does it it can't be entirely incorrect.

**Comment by FriedZombie** [comment]
It is partially incorrect, since the move is ignored. However the parameters should then still carry over.
Otherwise you could end up with breaking drill bits for example if the cnc cutter isn't running because of a double node.
Or in a more favorable case with a laser cutter, it doesn't cut.

In either case, it is not correct behavior, also not that often triggered either. So that could be that it went unnoticed perhaps. (as also with grbl)

 Btw should I also open an issue on grbl?

**Comment by wolfmanjm** [comment]
I just checked the code, and Sxxx IS set even if the G0/G1 does not change. So this is not an issue in smoothie.
Maybe it is a bug in your host not sending the command if the move does not change?
Look at line 1046 in Robot.cpp S is set always.

**Comment by wolfmanjm** [comment]
Also on lasers G0 NEVER cuts so specifying S0 on a G0 is somewhat redundant.
