### ISSUE TITLE
Delayed Telnet response

### ISSUE THREAD

**Issue by lalten** [Smoothieware/Smoothieware#1341]
I'd like the Smoothieboard to respond without much delay via Telnet so my host program can react to its responses directly. Any help is appreciated.

#### What were you doing?
I'm using the Smoothieboard in a cartesian portal as a manipulator for a robot. I control the endeffector with gcode, mostly `G1` and `G38.3`/`G38.5`. The code is streamed via Telnet. The communication is ping-pong because I need the output of e.g. the probe commands to know the endeffector position.

#### What did you expect to happen?
I expected the Smoothieboard to reply `ok` as soon as it received a command (`G1`) or a command was completed (`G38`). I expected very little delay, probably less than 10ms.

#### What happened instead?
Instead, all responses are delayed, by up to 500ms. If I strictly wait for every `ok` before sending the next command, I'll have a hard time getting over 2 gcodes per second.

#### Branch & Commit or Version of Smoothieware
Build version: edge-24da5ce, Build date: Jun 14 2018 12:13:18, MCU: LPC1769, System Clock: 120MHz
CNC Build 3 axis

#### Hardware model you are using (Make, and version)
Smoothieboard 0X v1.1

#### Host and Operating System running the Host
Ubuntu 18.04
The problem appears on all hosts, including Pronterface

#### Link to and console logs
Wireshark capture of some `M114.2` and responses:  
![image](https://user-images.githubusercontent.com/11611719/45046263-edacff00-b075-11e8-904f-29292c8851a7.png)
[telnet.pcapng.zip](https://github.com/Smoothieware/Smoothieware/files/2349523/telnet.pcapng.zip)

#### Link to running config and M503 results
config: https://gist.github.com/lalten/22a74f8c6838b6d512c87acd8bc81260

#### What did I try
Since this sounds like [TCP delayed acknowledgment](https://en.wikipedia.org/wiki/TCP_delayed_acknowledgment) I did try to set `TCP_QUICKACK`, but the Wireshark logs show that it doesn't seem to have an effect (altough I'm not sure I did this correctly, see below)
```python
import telnetlib
import socket

tn = telnetlib.Telnet('192.168.88.170')
tn.read_until('\n')

tn.write('M119\n'); tn.read_until('ok\r\n')
tn.write('M119\n'); tn.read_until('ok\r\n')
tn.write('M119\n'); tn.read_until('ok\r\n')

tn.get_socket().setsockopt(socket.SOL_TCP, socket.TCP_QUICKACK, 1)

tn.write('M119\n'); tn.read_until('ok\r\n')
tn.write('M119\n'); tn.read_until('ok\r\n')
tn.write('M119\n'); tn.read_until('ok\r\n')
```

**Comment by wolfmanjm** [comment]
I am sorry but there is nothing that can be done to improve this.

**Comment by lalten** [comment]
@wolfmanjm Could you give some more details please? Where does the delay come from?

**Comment by wolfmanjm** [comment]
Did you try with a USB or serial interface? I suspect the delay will be there as well, if not there is nothing we can do.
If the delay is there then you need to set the config option...

queue_delay_time_ms 0

See if that helps. If not the issue is in the telnet/tcp stack and that is something we cannot fix.

**Comment by wolfmanjm** [comment]
Ping pong is not supported under TCP/IP it will be very inefficient which is why pronterface does not use ping pong when connected via TCP.

**Comment by lalten** [comment]
I see. Apparently I have less than 1 ms delay on USB (without queue_delay_time set)!
![image](https://user-images.githubusercontent.com/11611719/45049146-04efea80-b07e-11e8-9ea3-98d4bd71fa2e.png)

**Comment by wolfmanjm** [comment]
Don't wait for the ok, it means nothing when using TCP/IP it certainly does not mean that the move has finished it simply means the command was received not even queued or planned.

Waiting for the ok in this context is your problem and is a misuse of the protocol.

**Comment by lalten** [comment]
I don't care so much about the ok, but one thing that is important is the probe position after G38. I need the probed position to calculate the next moves. And I would like to not have a 500ms pause without motion there because the "probe" is actually the motor current of a weed whacker attached at the tip ;)
