### ISSUE TITLE
M110 command is not working as described in Documentation

### ISSUE THREAD

**Issue by luc-github** [Smoothieware/Smoothieware#1347]
According https://github.com/Smoothieware/Smoothieware/blob/edge/src/modules/communication/GcodeDispatch.cpp#L86-L99

To reset line number seems need to type :
```
N{New Line Position} M110
```
but documentation http://smoothieware.org/supported-g-codes give different syntax
```
M110 N{New Line Position}
```
![image](https://user-images.githubusercontent.com/8822552/46071193-cbdbff00-c17f-11e8-8a01-1d6aabda8293.png)

**Comment by wolfmanjm** [comment]
it seems to work fine. just change the wiki

**Comment by luc-github** [comment]
you mean M110 N{New Line Position}  work fine ?
It is not on my side

**Comment by wolfmanjm** [comment]
As far as I know ALL hosts send Nxxx M110 to reset the line number. This seems to be the defacto standard for reprap.
It would be easy enough for you to add code to allow M110 Nxxx if you insist on going against the defacto standard.
I'd also check to see what the NIST standard says about M110 (if it says anything as I suspect this is a reprap addition).

**Comment by luc-github** [comment]
No I am fine with current behaviour I have checked issue before posting https://github.com/Smoothieware/Smoothieware/issues/1228
So for me was doc issue but I just did not understood your statement `it seems to work fine`
