### ISSUE TITLE
Preheat doesn't work after heater rename

### ISSUE THREAD

**Issue by pmarkiewicz** [Smoothieware/Smoothieware#1360]
Following http://smoothieware.org/multiple-extruders#1-hotend-two-extruders I renamed 
temperature_control.hotend to temperature_control.heater
After that preheat command don't set extruder temperature.

SENDING:M115
FIRMWARE_NAME:Smoothieware, FIRMWARE_URL:http%3A//smoothieware.org, X-SOURCE_CODE_URL:https://github.com/Smoothieware/Smoothieware, FIRMWARE_VERSION:edge-a06bb6a, X-FIRMWARE_BUILD_DATE:Nov 30 2018 20:34:40, X-SYSTEM_CLOCK:100MHz, X-AXES:5, X-GRBL_MODE:0, X-CNC:0, X-MSD:1

SENDING:M503
; No config override
;Steps per unit:
M92 X160.68240 Y160.73912 Z3508.00000
;Acceleration mm/sec^2:
M204 S800.00000
;X- Junction Deviation, Z- Z junction deviation, S - Minimum Planner speed mm/sec:
M205 X0.03000 Z-1.00000 S0.00000
;Max cartesian feedrates in mm/sec:
M203 X66.66666 Y66.66666 Z2.00000 S-1.00000
;Max actuator feedrates in mm/sec:
M203.1 X500.00000 Y500.00000 Z28.00000
;E Steps per mm:
M92 E407.4000 P57988
;E Filament diameter:
M200 D1.7500 P57988
;E retract length, feedrate:
M207 S1.5000 F3300.0000 Z0.0000 Q6000.0000 P57988
;E retract recover length, feedrate:
M208 S0.0000 F480.0000 P57988
Got rubbish reply from COM5 at baudrate 115200:
Maybe a bad baudrate?

**Comment by wolfmanjm** [comment]
then do not rename it.

**Comment by pmarkiewicz** [comment]
Nice answer, so now I should raise bug against documentation? :)
