### ISSUE TITLE
Feature request: M109 with R parameter like in Marlin

### ISSUE THREAD

**Issue by ghost** [Smoothieware/Smoothieware#1416]
It'd be great to have M109 G-code integrated with an R parameter to control falling temp too.

In Marlin I see in description:

"M109 - Wait for Hotend Temperature
This command optionally sets a new target hot end temperature and waits for the target temperature to be reached before proceeding. If the temperature is set with S then M109 waits only when heating. **If the temperature is set with R then M109 will also wait for the temperature to go down.**"

**Comment by wolfmanjm** [comment]
We use the temperatureswitch for this kind of thing. However there is a pull request that implements this feature. #1279

**Comment by ghost** [comment]
Tnx
