### ISSUE TITLE
Tool is switched just by changing temperature

### ISSUE THREAD

**Issue by compunited** [Smoothieware/Smoothieware#1429]
According to the GCode specification i read the tool should be switched by using the T0/T1 command
Smoothieware is changing the tool just by this

M106 S128
M104 S240 T0

If I forget to manually add a T1 line after the M104 command the print fails

**Comment by wolfmanjm** [comment]
That is correct, Tn anywhere on the line will switch the tool. It would be illegal gcode to have Tn as a parameter.

This is a hack to comply with reprap gcode. Real NIST standard GCode Tn would only be executed when followed by M6.

To allow for reprap incorrect gcode, a Tn anywhere on the line would be executed first to switch the tool (or hotend/extruder in this case).
