### ISSUE TITLE
SCARA home_z_first error

### ISSUE THREAD

**Issue by alfie0** [Smoothieware/Smoothieware#1450]
Latest firmware version

arm_solution     morgan SCARA
scara_homing     true
home_z_first       true

X and X axis always start to move first.

Running G28 Z0, X-Y axis will also move together first.

**Comment by wolfmanjm** [comment]
Scara has a different homing protocol, so I suspect home z first does not apply  to it.
contact @qharley for more details, he handles the scara stuff.

**Comment by qharley** [comment]
Homing in SCARA defaults to all moving together.  I will check if there are
differences between my branch and Smoothie/edge

**Comment by qharley** [comment]
Try my branch for SCARA bots.  There are some features that wil not be
incorporated into Smoothie/edge that may come in handy.
I changed the homing routine to bring back the "Home All" function.

**Comment by qharley** [comment]
https://github.com/RepRapMorgan/Smoothieware

**Comment by qharley** [comment]
We are in lockdown here in South Africa.  I will try to work on an update to the SCARA code that will hopefully please the Smoothie mods

**Comment by alfie0** [comment]
I try G28 Z0 in detail, XYZ axis does moving together, but the X axis moves very slowly. I hope that the Z axis can be homing alone. Thank you.

**Comment by qharley** [comment]
I just checked.  If you do G28 Z in MorganSmoothie branch it will only home the Z-axis

**Comment by alfie0** [comment]
Try different settings and firmware are not good, G28 Z axis and X-Y axis always move together, do not know what reason.




[config - Morgan.txt](https://github.com/Smoothieware/Smoothieware/files/4422065/config.-.Morgan.txt)
