### ISSUE TITLE
Ethernet 100mbps RFI issue and possibility for software workaround at 10mbps

### ISSUE THREAD

**Issue by frazierjason** [Smoothieware/Smoothieware#1500]
Smoothieboard 5x emits strong Ethernet RFI whether idle or printing, and I am looking for a software fix.  Is it possible for Smoothieware to manage Smoothieboard's Ethernet link speed and force it to 10baseT, and if so can this be exposed to the user for configuration?

I have a Smoothieware 5x board, and I am also an amateur radio operator who is finally getting serious about hunting down persistent radio frequency interference (RFI) in my house. The Smoothieboard emits a fairly strong pair of carriers across a bunch of harmonic frequencies and I have multiple antennas picking up these RFI in the 14MHz and 28MHz ranges. Smoothieboard is not the only culprit, I also have a Cisco Linksys VoIP appliance and one of the many rebranded Chinese Security DVR systems -- both these also emit the exact same frequencies. No amount of toroid windings is taming the RFI from these Ethernet cables.

But! if I put a managed switch into the picture and force these devices' switch ports from Auto negotiate down to always run 10baseT (10mbit) full duplex, the RFI disappears. All these devices' (Smoothie included) use cases are served just fine at 10mbps link speed. Unfortunately I only have one managed switch and I need it elsewhere. Smoothieware devs, can you help clean up this ham's radio spectrum with a software fix? (Clarify: RFI is to be expected during 3D printer operation, but not 24/7 idle Ethernet noise)

> M115
FIRMWARE_NAME:Smoothieware, FIRMWARE_URL:http%3A//smoothieware.org, X-SOURCE_CODE_URL:https://github.com/Smoothieware/Smoothieware, FIRMWARE_VERSION:edge-bdb141f, X-FIRMWARE_BUILD_DATE:Jan 12 2020 10:21:20, X-SYSTEM_CLOCK:120MHz, X-AXES:5, X-GRBL_MODE:0, X-CNC:0, X-MSD:1
ok

#### What did you expect to happen?

Ethernet carriers at 100mbps should be filtered or shielded on the board.

#### What happened instead?

Ethernet carriers at 100mbps link speed are easily picked up by shortwave antennas outside the home, making it difficult to carry amateur radio conversations and digital modes.

#### Branch & Commit or Version of Smoothieware

> M115
FIRMWARE_NAME:Smoothieware, FIRMWARE_URL:http%3A//smoothieware.org, X-SOURCE_CODE_URL:https://github.com/Smoothieware/Smoothieware, FIRMWARE_VERSION:edge-bdb141f, X-FIRMWARE_BUILD_DATE:Jan 12 2020 10:21:20, X-SYSTEM_CLOCK:120MHz, X-AXES:5, X-GRBL_MODE:0, X-CNC:0, X-MSD:1
ok

#### Hardware model you are using (Make, and version)

    eg Smoothieboard 5X V1b

#### Host and Operating System running the Host

    Windows 10 20H2
    
#### Link to running config and M503 results

    n/a?  This issue happens all the time even when idle.

**Comment by wolfmanjm** [comment]
You will need to edit the source code and build your own version.
Basically you will need to change this line: 
https://github.com/Smoothieware/Smoothieware/blob/edge/src/libs/Network/Drivers/LPC17XX_Ethernet.cpp#L345
to
`write_PHY (EMAC_PHY_REG_BMCR, EMAC_PHY_FULLD_10M);`
