### ISSUE TITLE
error smoothieboard cnc-machine  (smoothieboard V1)

### ISSUE THREAD

**Issue by Aaronvanr** [Smoothieware/Smoothieware#1525]
I have an error with smoothie board.
With the basic firmware of smoothieboard that was pre-installed on our V1 smoothieboard, we were able to control 3axis from our cnc machine using the config file. We set up a new firmware so we could control our spindle. After installing the new firmware it fails to control the 3 axis and the spindle. Hereby we ask for your help on which firware we need. 

Thanks in advance

**Comment by wolfmanjm** [comment]
you will need to give a little bit more information, like your config the results of version etc.

However this is not the forum for asking for help as this is not a bug I am closing this issue.
Try asking on one of the other forums we use for helping, there is one on IRC and one on facebook as well as several other places.
