### ISSUE TITLE
Adding and subtracting steps? 

### ISSUE THREAD

**Issue by lateforwork1000** [Smoothieware/Smoothieware#1527]
new issue 

Hay I'm having a problem calibrating my laser I notice that im getting additional steps not sure what is causing it but ill explain as best as I can. 

when I calibrate my laser machine steps per mm to cut out a 5inch square it will cut out a perfect 5inch but when I cut out a 2inch square it will loose steps 1.98 of a inch and when I cut out a 1 inch square it be 97.5. But if I calibrate my machine to 2inch square it will cut out a perfect 2inch square, and when I cut out a 5inch square it will be 5.02. this is happening on both axes. I tried a circles the lines to meet up perfectly.  I installed Arduino with gbrl and it perfect squares. I really don't know what is causing this, at this point I'm assuming its the smoothie board something is adding and subtracting steps. any ideas what this could be?

**Comment by wolfmanjm** [comment]
Nothing in smoothie adds or subtracts steps I am afraid. If you are using external drivers make sure the polarity of the step pulse is correct. FWIW you should not need to calibrate steps/mm as it is a fixed amount.
Sorry this is not really a bug or issue, it is probably a setup issue so will need to be handled on the support forum.
