### ISSUE TITLE
Error xhen installing the toolchain for windows !

### ISSUE THREAD

**Issue by manuprendlair** [Smoothieware/Smoothieware#1530]
Hi,

this morning I try to install the toolchain for windows and I got this error 

![image](https://github.com/Smoothieware/Smoothieware/assets/10948827/54f3de2c-45fd-43b9-bc18-5e1711f73c94)

Could have I help on this please ?

Regards

**Comment by wolfmanjm** [comment]
try this https://github.com/Smoothieware/Smoothieware/pull/1470
