### ISSUE TITLE
Serial Driver on OS X 10.6

### ISSUE THREAD

**Issue by dognotdog** [Smoothieware/Smoothieware#203]
There is some issue with the OS X 10.6 usb/serial drivers being buggy, and it seems like [this SO thread](http://stackoverflow.com/questions/5009593/acessing-a-serial-to-usb-device-with-i-o-kit) recommends changing the last field of CDC_callmgmt in USBCDC.cpp to 1 instead of 0 as it is now, to placate the driver. Can someone test this?

It seems like 10.7 and forward of OS X have fixed the issue, and smoothie is recognized just fine.

**Comment by wolfmanjm** [comment]
very old dormant issue
