### ISSUE TITLE
Really long strings causes freeze

### ISSUE THREAD

**Issue by TopherMan** [Smoothieware/Smoothieware#241]
I am using the newest version of Cura for my slicing, and the only issue I have is that it appends a string that has info about the profile that's nearly 2,000 characters long. It's commented out, so it shouldn't do anything, but Smoothie freezes when it reaches the string. Here's an example from the last three lines of a Cura .gcode file.

```
G1 X0 Y160 F6000;move to center
M84                         ;steppers off
;CURA_PROFILE_STRING:eNrtV01v20YQvapCf8QeWzRWSEqy4xi8tLB9qYsCMdDEF2JFjqStSS6xXFqWBP33vv0gTclyGyMpUBTRwSZnZ2bn483bZc7XpJIlicVSx8EoGqx4nid6KdL7kuoaorOBIq14qoUsEyr5LKf4VjU0qGUusiS3Dp4MRpPBXMBFRmUt9Dp+FwxKudnklNRiQ/A3ng4qJUqd1BVRFp8G/lVTUZHiulHQei6LjgnHx4STTjij7MBt3VSVVDr+TZY0qHKu51IVCc+WVCM9J/Y6SdbwPKFHrRq7dsXzmkxuvCD4zgT+a1JxNDqfPhebcJ8Jx8eEk75wnstVHAbBKOhX3VVqeiDlhWxKjf33pDZqvxSejqb9tUKUCV4eKI+n+1apLGaiXLjG7luIYq8MAVzOpNay2ENJNB3I2Z+Uoq2ivI9NqPKBVM4rG5GFltvaZ4MkWz8OQk4cBQNRWgC5d+MolTK3sXusiYJilJy3cMw8Hu8FupaLkpCOTd+LFryKJ/65TSincqGXcWiLalxZ3zAxz27rs+nTS1LwRxtyF8scUsCKIHXCJXFMg5hrjxQ3HlpW/WlxGTuJzdIXCYF0uLNy6zrqAJs8rgGYWvMyJTuTrXzTF8PJTImiXwO4UHyOvLlaiBJls29Woa54anoejrzOjNe019RxT25MViJDzSwlGDlGjNScp/tG0eFi3zJC1o/JUiol0LikKS2QDeOsK0p4N2Qv68yO6iBAWVGZzISujykAv4aPHpC1FjpdmrydWpU3KAyqBdQt4h/yKhyOWiinZJJIHuOT8EC0huh71F3p0SKVGcUXH3KRUsa26B5QWdCOcf2ebTO+3pm/GoKtQe5uePEzr0XKatIaYdTv2a8GesxxMEzyHiXv2B/IHDrbfV7esSug5L3druNauP7d8B4z+2DNM6Pb9MpTDEOtMmfoKMdxxa7oiVZu70XPKpW17luZ993wOgqZ/12AzBTSeuB5Q/Xw+jzoVvgM4G80sUoiTHQTaQ9vwuCsVbCFZCuhl0wviWHqmJzP4f0d+xiwT4HxjkFhH99+YloyjB+jMqsxW7VVugt8CEbp7rnKeeT9QPGyi4tdKEITWC3nesXVU3jGwVzJUr/Naa7fbgwJWSc92ycnG1LShm05MgMGHLcMr0N2FQXYcXxg4RXZuCiQJzNMwhBpev/6TRhfcFHarbZ9et0NkH0LzcsyY9e/4NEUfcI+HNmgF5ZBIuCqbAtuwknwooHVyxhO2Z4J+0HM2Vo2bIlomNA/IqmQfcYP3cB5jBHdgwkyuzxBduMg+Adje2Y5/LSg5Qx8gPhwyBMz1AyPVsPdSN6YRmNXAr8BBQWZbpjlCsCocWEwu9/9BH5EDNPDCndwayq/EUed2zi6GOiBSlZI4+z85RSOzwi2N7gNT4PDzd3eCN/x0fDm3eRl37WmCneg2rTnO/djF1dmyBAZf7RucIIN7BhGB4T2jcX+KywGLIa4tr2AQ4tbf6FlmVyVLJwWxfA2/BLmCoPjzBUGX5W67F4n2+O32N3wNviKOfxrSex3BcgIz5gFMnAyGo0MIUcvMPJt8EpSNjbhNyJ/JZHj08US+ceTCPNo/nwxpT/N9t8m9dLcv0G0NlDz8cAEGLrRbewrvv58Wn/94dJ9QfRvsZ3w6fbgPm72lKykp6EIxJPSKK0f4kEJ9Lm7cgv2G39UmRXmlszJ0yesEUvRPJVsTA3Mgv9MYxt/oLAVem3m1BSQ36PL6KoRZvArNVvaXq29+3rkJ/l/A9lDoB5i6+vcQj7nQnK39a3C4b3F7QFfoJ7x2pLj0rI9+IDasU/PRYeM2TH2qXc1qFfmW+3S01l3MbFSlFaviByO0kYpm2bLfKYIttgGc630DVstYVB5UnZHddHkWlR5x+yqBx7T//Epu5oGQXsEDW+3reLOpYqPW5egecA16c4+bI7md3ng7S9rojwP
```

Currently I'm using a plugin I wrote for Cura to remove it automatically, but I figured it was a good idea to post the issue here.

**Comment by ryanhathy** [comment]
In "end.gcode" under the "Start/End-GCode" tab in Cura, delete the line ";{profile_string}" and the cura profile string will no longer appear in your gcode.
I'm using Cura 15.02.1, I don't know if this applies to other versions.

Sorry to revive a dead thread, but I just wanted to place this information here for anyone reading this thread trying to solve this problem.

**Comment by wolfmanjm** [comment]
it isn;'t an issue anymore it was fixed in smoothie.

**Comment by ryanhathy** [comment]
Thanks, but there may still be people like me that are behind the times and still need to remove the cura profile string from the gcode. :) 
I'm using Cura with Linux CNC to 3D print on my CNC machine, so I don't have a smoothieboard, but I do have the ingredients to make a smoothy. :) Mmm, that sounds good, I think I'll go make one...................
