### ISSUE TITLE
smoothie's usb drive on macosx takes time to startup. There are timeouts listed in the system log. 

### ISSUE THREAD

**Issue by gkbeer** [Smoothieware/Smoothieware#261]
In addition to the drive being slow to appear. 

System log entries at time usb is connected to mac.  (Mavericks)

After the initial entries, there are two reports of timeouts that take ~30sec each. The drive becomes available coincident with the last entry listed below. 

Oct 24 21:33:01 Fang kernel[0]: USBMSC Identifier (non-unique): 0C0C0D165357183C4F75DBBAF5000003 0x1d50 0x6015 0x100, 1
Oct 24 21:33:01 Fang kernel[0]: AppleUSBCDCACMData: Version number - 4.2.1b2, Input buffers 8, Output buffers 16
Oct 24 21:33:01 Fang kernel[0]: AppleUSBCDC: Version number - 4.2.1b2
Oct 24 21:33:33 Fang kernel[0]: USBF:    53291.259    AppleUSBOHCI::Found a transaction past the completion deadline on bus 0x6, timing out! (Addr: 4, EP: 5)
Oct 24 21:34:04 Fang kernel[0]: USBF:    53322.277    AppleUSBOHCI::Found a transaction past the completion deadline on bus 0x6, timing out! (Addr: 4, EP: 5)
Oct 24 21:34:17 Fang.local fseventsd[46]: check_vol_last_mod_time:XXX failed to get mount time (25; &mount_time == 0x1079783d8)
Oct 24 21:34:17 Fang.local fseventsd[46]: log dir: /Volumes/SMOOTHIE32/.fseventsd getting new uuid: 7F2C8504-EDBF-4AA0-A628-F1A1C2DF4C01

**Comment by cederom** [comment]
Confirming the problem. UMS also seems to corrupt the filesystem. Please consider msdosfsck on boot.

**Comment by docdawning** [comment]
Possibly the same problem for me - I don't think I've ever got OS X 10.11 to mount the drive successfully. I've got by using a Windows 7 VM and routing the USB reader I have to it. that's definitely annoyingly round-about though. I'm not really sure what to blame though.

**Comment by arthurwolf** [comment]
Yeah this is a wêll known problem with MacOS misbehaving : when a card is inserted, it'll go read all over it, and write a load of crap on it. Not sure how to teach it not to do that.

**Comment by JesperKrogPoulsen** [comment]
> On 03 May 2016, at 17:57, Arthur Wolf <notifications@github.com> wrote:
> 
> Yeah this is a wêll known problem with MacOS misbehaving : when a card is inserted, it'll go read all over it, and write a load of crap on it. Not sure how to teach it not to do that.
> 

You can turn off indexing using 

sudo mdutil -i off /path_to_volume

from the terminal. /path_to_volume is usually /Volumes/something. Do an ls /Volumes if you aren’t sure.

I’m not sure if it will prevent Spotlight from indexing the card, but you can add it to the privacy tab in the Spotlight preferences.

Also, if you delete the .Trashes folder and create an empty .Trashes file, it will prevent OS X from creating a new trashcan, like this:

rm -fr .Trashes
touch .Trashes

again from the terminal.

/Jesper

**Comment by wolfmanjm** [comment]
probably unfixable.
