### ISSUE TITLE
Feature Request: Auto shutdown of heaters if left running w/o starting a print

### ISSUE THREAD

**Issue by gkbeer** [Smoothieware/Smoothieware#305]
For consideration. Low Priority.  

Distractions do happen. 

Implement a timer to shutdown the heaters, in the event no printing is started within predefined time limit. 

Timer would be abandoned if the printer moves before limit is met.

**Comment by wolfmanjm** [comment]
there really is no way to know when a print has started vs jogging. So I don't think this is practical.
