### ISSUE TITLE
PID Autotune needs configurable pwm frequency

### ISSUE THREAD

**Issue by logxen** [Smoothieware/Smoothieware#347]
Ideally it should use the frequency of the specific heater requesting the tuning

**Comment by hyperair** [comment]
max_pwm != pwm_frequency. I recently had issues with this while trying to use an SSR with smoothieboard with pwm_frequency=8. Autotune wouldn't work (LED blinks erratically despite Smoothieware reporting @255), but M140 works.

**Comment by wolfmanjm** [comment]
I may misunderstand the issue but the PWM frequency is set on the ADC pin, so autopidtune does use that. which is set by the associated temperature control.
