### ISSUE TITLE
Active EndStops 

### ISSUE THREAD

**Issue by Veloce7** [Smoothieware/Smoothieware#589]
Is there a reason why active endstops aren't being used in Smoothie while jogging? Is this possible?

**Comment by arthurwolf** [comment]
Hey.

What do you mean by "active endstops" exactly ?

Cheers.

On Mon, Feb 2, 2015 at 8:01 PM, Veloce7 <notifications@github.com> wrote:

> Is there a reason why active endstops aren't being used in Smoothie while
> jogging? Is this possible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/589>.
>



-- 
Courage et bonne humeur.

**Comment by Veloce7** [comment]
The endstops only work while homing and not while jogging around. Is there a setting or someway I can set them to always be active?

**Comment by arthurwolf** [comment]
Yep, see here : http://smoothieware.org/endstops#limit

Cheers :)

On Mon, Feb 2, 2015 at 8:41 PM, Veloce7 <notifications@github.com> wrote:

> The endstops only work while homing and not while jogging around. Is there
> a setting or someway I can set them to always be active?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/589#issuecomment-72523110>
> .
>



-- 
Courage et bonne humeur.
