### ISSUE TITLE
opendir crashes for files with long filename

### ISSUE THREAD

**Issue by minad** [Smoothieware/Smoothieware#616]
e.g. ls /sd/model/smoothie/Sidecar_Controller_Housing_for_5XC_Smoothieboard.zip via telnet

**Comment by wolfmanjm** [comment]
probably a fixed length buffer somewhere in mbed...You  need to find it and truncate the file name.

**Comment by minad** [comment]
Yes, I just didn't debug it yet. Just to keep it on the todo.
