### ISSUE TITLE
Wrong progress reports

### ISSUE THREAD

**Issue by minad** [Smoothieware/Smoothieware#619]
The number of bytes in total is wrong. Maybe some fs problem.

~~~
0 % complete, elapsed time: 1687 s, est time: 1245307818 s
SD printing byte 5652/3735928559
~~~

Also this elapsed time report is wrong. I just let it run for a few seconds.
This reports somehow the full 4GB?

Someone else seeing this?

**Comment by minad** [comment]
maybe elapsed time is about 30 minutes since I aborted the print before. Then it also showed "SD printing byte 0/3735928559". I have to investigate a bit better what is going on here.

**Comment by wolfmanjm** [comment]
Maybe this is a file you uploaded via p9? and the size is screwed up for some reason. I have never seen this issue with files uploaded or written using msd or file upload. 
Elapsed time also works pretty well, but it is possible an abort does not reset it properly.

**Comment by minad** [comment]
Yes, but the file is playing correctly. Also ls reports correctly. For me the issue seems limited to progress. I will investigate and come back here.

Am 18. Februar 2015 11:09:43 MEZ, schrieb Jim Morris <notifications@github.com>:

**Comment by arthurwolf** [comment]
does ls -s show it with the right size ?

On Wed, Feb 18, 2015 at 11:33 AM, Daniel Mendler <notifications@github.com>
wrote:

> Yes, but the file is playing correctly. Also ls reports correctly. For me
> the issue seems limited to progress. I will investigate and come back here.
>
> Am 18. Februar 2015 11:09:43 MEZ, schrieb Jim Morris <
> notifications@github.com>:
> >Maybe this is a file you uploaded via p9? and the size is screwed up
> >for some reason. I have never seen this issue with files uploaded or
> >written using msd or file upload.
> >Elapsed time also works pretty well, but it is possible an abort does
> >not reset it properly.
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >
> https://github.com/Smoothieware/Smoothieware/issues/619#issuecomment-74840534
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/619#issuecomment-74843503>
> .
>



-- 
Courage et bonne humeur.

**Comment by minad** [comment]
@arthurwolf 

~~~
progress -b
SD printing byte 725/3735928559
ls -s /sd
castle.gcode 2640289
~~~

**Comment by minad** [comment]
3735928559 = deadbeef

is this what malloc does?

**Comment by minad** [comment]
lol i think i found the bug by simple code inspection. I use M32 and you forgot to initialize file_size there. There is also quite some code duplication and this can result in such a bug. Srsy guys?

**Comment by wolfmanjm** [comment]
I didn't write or add the Mxxx stuff someone else did, use git blame before you blame me.

**Comment by minad** [comment]
I don't blame anyone. Here is the fix :grinning:

**Comment by minad** [comment]
But this code needs cleanup badly.
