### ISSUE TITLE
Heat and wait gcode bypassed by disconnected thermistor

### ISSUE THREAD

**Issue by tempo502** [Smoothieware/Smoothieware#646]
I just tried to print a file with my thermistors disconnected. This file usually takes a significant period of time to preheat before starting. To my surprise, with the thermistors disconnected and the LCD reading 999C, the machine immediately sprang into action and started trying to print.

**Comment by arthurwolf** [comment]
Could you reproduce this and tell us what M105 returns ?
Thanks.

On Mon, Mar 23, 2015 at 11:55 PM, Ryan Carlyle <notifications@github.com>
wrote:

> I just tried to print a file with my thermistors disconnected. This file
> usually takes a significant period of time to preheat before starting. To
> my surprise, with the thermistors disconnected and the LCD reading 999C,
> the machine immediately sprang into action and started trying to print.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/646>.
>



-- 
Courage et bonne humeur.

**Comment by tempo502** [comment]
I'm running prints from the LCD / external SD card. Give me time to find a USB cable, the roomba ate my last one...

**Comment by wolfmanjm** [comment]
Actually I know what the problem is, the point is what we want to happen there.
The disconnected thermistor makes the read temp INF, but the target temp is set to UNDEFINED which is -1, hence that M109 test passes. Setting UNDEFINED temp to INF would make M109 hang indefinitely.
Not sure that is what we want.

**Comment by tempo502** [comment]
My personal preference is that it refuse to play files and/or abort active commands while the sensor is disconnected. That would be in line with other popular platforms.

**Comment by tempo502** [comment]
If the "abort active commands" route is chosen, it would be reasonable to wait a certain number of updates/seconds first in case the issue is an intermittent wire break.
