### ISSUE TITLE
Mac dot files "._" on display

### ISSUE THREAD

**Issue by Veloce7** [Smoothieware/Smoothieware#660]
When copying gcode files from a Mac to a micro SD card to print from a smoothie compatible display, two files show up on the display. The unnecessary one begins with "._". Can these files be hidden from displaying?

Thanks,
Mark

**Comment by wolfmanjm** [comment]
they already are, try the latest firmware.

**Comment by Veloce7** [comment]
I’m pretty sure I’m running the latest FW from two months ago. I’ll double check

Thanks,
Mark

**Comment by triffid** [comment]
On 25 April 2015 at 15:26, Veloce7 <notifications@github.com> wrote:

> from two months ago.
>

In a project that moves as fast as smoothie, that's barely recent, let
alone latest :P

**Comment by WZ9V** [comment]
Yes but it is the latest that has been put into the firmware directory.

**Comment by Veloce7** [comment]
Is there another place I should be looking to find more recent firmware?

**Comment by triffid** [comment]
http://triffid-hunter.no-ip.info/Smoothie-edge.html

**Comment by Veloce7** [comment]
Thanks Michael
