### ISSUE TITLE
M500 sent from the display custom menu not updating config-overide file

### ISSUE THREAD

**Issue by Veloce7** [Smoothieware/Smoothieware#661]
Sending M500 from the display custom menu doesn't save new values to the config-overide file

**Comment by wolfmanjm** [comment]
I tested this with current edge and it works exactly as expected.
Check your definition in config.. this works for me...

```
custom_menu.save.enable                    true              #
custom_menu.save.name                      Save_Settings     # 
custom_menu.save.command                M500              #
```
