### ISSUE TITLE
G30 doesn't respect F parameter

### ISSUE THREAD

**Issue by sorki** [Smoothieware/Smoothieware#677]
In documentation there's:

    Simple Z probe at current XY, reports distance moved down until probe triggers, optional F 
    parameter sets feedrate

but F is completely ignored. There's optional Z heigh to return to after probing.

**Comment by sorki** [comment]
Related to #614

**Comment by wolfmanjm** [comment]
fixed docs. g30 never had an F parameter

**Comment by wolfmanjm** [comment]
FYI the wiki is a public Wiki, if the docs are wrong just correct them.

**Comment by sorki** [comment]
Does it make sense to add F param to G30? I need to adjust feedrate from host as pcb probing with tool has to be done slowly.

**Comment by wolfmanjm** [comment]
Not really, the speed of the probe is set in the config file. the Wiki has the documentation for that.
