### ISSUE TITLE
Pulse Input counter

### ISSUE THREAD

**Issue by thinkl33t** [Smoothieware/Smoothieware#750]
For laser cutters, it would be useful to be able to read a pulsed input and apply a formula to it to read things like Extraction Fan RPM (on a standard 3-pin PC fan, or just with a hall effect sensor next to a DC motor), and Coolant flow rate (using a sensor such as http://www.ebay.co.uk/itm/Water-Flow-Sensor-Switch-Meter-Coffee-Dispenser-Counter-Fluid-Control-0-3-6L-min-/231619637580?hash=item35ed9b314c).

Also useful as part of this would be minimum and maximum thresholds, for example to pause lasering if the coolant flow falls below a set value.

**Comment by wolfmanjm** [comment]
this is almost exactly what the filament detector already does. Check it out.
