### ISSUE TITLE
Req: If configured for Delta, inhibit motion if endstop is hit during printing

### ISSUE THREAD

**Issue by BrianGilbert** [Smoothieware/Smoothieware#753]
Smoothie currently doesn't inhibit motion when an endstop is hit except for when you home all.

I was printing a vase the other day and as it got towards the top the carriages were hitting the top of the printer and smoothie just kept going, it would be great if it would stop the print.

Luckily I was only air printing as a demo without filament.

**Comment by wolfmanjm** [comment]
This is already implemented as of a few weeks ago, just enable limits in config, see the wiki in the endstops section.
