### ISSUE TITLE
LCD Blanking out after print is done

### ISSUE THREAD

**Issue by WZ9V** [Smoothieware/Smoothieware#756]
Using either Pronterface (USB) or exernal SD Card, my LCD display (ASMZ Mini) is blanking out after a print and requires a reset to bring it back.  This is on  the following version - 

Build version: edge-ed25d57, Build date: Oct 17 2015 22:04:52, MCU: LPC1768, System Clock: 100MHz

I was not seeing this behaviour on the late September/early October edge versions.

**Comment by gddeen** [comment]
Is there a power off m code?
The USB keeps some electronics up?

**Comment by wolfmanjm** [comment]
This is a hardware issue, as there is nothing in S/W that would do that. I suggest you check your wiring, if it is too long it could do that.

**Comment by WZ9V** [comment]
Same wiring that NEVER did it before.  I'll roll back to September and see if it persists.

**Comment by WZ9V** [comment]
Yup, your right.  Despite it all working correctly yesterday, something weird is happening today.  All I can figure is I must have done something (like changed a wire position) when I swapped in the new Z-probe.
