### ISSUE TITLE
Feature Request: Support for AD8495

### ISSUE THREAD

**Issue by errolt** [Smoothieware/Smoothieware#757]
Hi wolfmanjm,

Please consider adding support for Thermocouples connected via the AD8495 chip.

It is analog with a straight 5mV/C output. The circuit is very simple and easy to retrofit with a baord like this: https://www.adafruit.com/products/1778

Thank you,
Errol

**Comment by wolfmanjm** [comment]
Thermocouples are already supported via the SPI interface available here... http://shop.uberclock.com/collections/smoothie/products/spi-thermocouple

I have no plans to add the above interface. I do not have one to test either.
If you want this you will need to add it yourself or get someone to add it for you.

**Comment by errolt** [comment]
Last time I heard there was issues with multiple spi-thermocoules on the same bus, add to that mix an spi lcd and it adds even more fun. :)

Anyway, no worries, I'll look at adding it.

**Comment by arthurwolf** [comment]
@errolt If you need any help implementing this, don't hesitate to ask

**Comment by wolfmanjm** [comment]
@errolt I will fix the SPI issues for the multiple thermocouple issue.
Note that when you add the support for the analog version, you will need to use a spare ADC port, you will not be able to use one of the thermistor ports. I think there maybe at least one spare ADC port you can use. The reason you need to use a raw ADC port is that the thermistor ports have external components designed to read a resistance not a voltage, so reading a voltage is made hard because there is a pullup resistor to AVCC which usually overpowers the amplifiers in these analog circuits.

**Comment by errolt** [comment]
This amp claims to have a 7ma output drive, which should be fine driving the 4k7 resistor, which will draw 0.7ma. It also actively measures the amp's output and compensates for any "losses".

If the resistor do give me problems then I will just remove it...

**Comment by errolt** [comment]
I have added it to my branch. You where right, it was very easy to add. Also works fine on the normal thermistor inputs.

**Comment by arthurwolf** [comment]
Hey. Can you point me at your code in your branch ?

Cheers.

On Fri, Nov 6, 2015 at 10:58 AM, errolt <notifications@github.com> wrote:

> I have added it to my branch. You where right, it was very easy to add.
> Also works fine on the normal thermistor inputs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/757#issuecomment-154367769>
> .
>



-- 
Courage et bonne humeur.

**Comment by errolt** [comment]
Hi Arthur,

I don't know if I followed your coding standards.

Code: https://github.com/errolt/Smoothieware/commit/9cee995ddbe7c073958de722d49dc9fd3d052872

Thank you,
Errol

**Comment by wolfmanjm** [comment]
looks good to me... if you want to do a pill request feel free to.

**Comment by arthurwolf** [comment]
Yep looks very good, please do a pull request, and ping me so I can update
the documentation.

On Sat, Nov 7, 2015 at 7:52 PM, Jim Morris <notifications@github.com> wrote:

> looks good to me... if you want to do a pill request feel free to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/757#issuecomment-154738621>
> .
>



-- 
Courage et bonne humeur.

**Comment by errolt** [comment]
Will do, as soon as I can figure out how to do a pull request on a single commit. Looks like a few commandline commands. Will try as soon as I can.

**Comment by errolt** [comment]
https://github.com/Smoothieware/Smoothieware/pull/765
