### ISSUE TITLE
Print "Calibration Successful" or "Unsuccessful Calibration" to display

### ISSUE THREAD

**Issue by Veloce7** [Smoothieware/Smoothieware#758]
I like to run auto calibrations from a Custom menu on the printer display. It would be a nice feature to print to the Smoothie Display weather or not the calibration was successful or not. This message could remain on the display for a preset amount of time or until the user interacts with the display.

**Comment by arthurwolf** [comment]
Hey.

I think that'd require the calibration routine to issue a M117 at the end
of calibration to report success. Not sure how/if that can be implemented.

Cheers.

On Sat, Oct 31, 2015 at 8:17 AM, Veloce7 <notifications@github.com> wrote:

> I like to run auto calibrations from a Custom menu on the printer display.
> It would be a nice feature to print to the Smoothie Display weather or not
> the calibration was successful or not. This message could remain on the
> display for a preset amount of time or until the user interacts with the
> display.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/758>.
>



-- 
Courage et bonne humeur.
