### ISSUE TITLE
stepper fequency limits ?

### ISSUE THREAD

**Issue by valpoder** [Smoothieware/Smoothieware#767]
Good day:

First of all  , congratulations for such great project !!!

Small question , i know GRBL project claims to have 30Khz free jitter stepper frequency limit for the avr processors.

having a faster and more powerfull processor , do you have an idea of what the stepper frequency limit would be for the smoothieboard firmware ??

thanks and best regards to everyone !!!

**Comment by arthurwolf** [comment]
Hey there.

Smoothie's maximum frequency is 100kHz :)

Cheers !

**Comment by valpoder** [comment]
very impressive !!!!  thanks for such a fast answer  !!
