### ISSUE TITLE
stabilization time

### ISSUE THREAD

**Issue by valpoder** [Smoothieware/Smoothieware#776]
Good day:

Small question, does smothieboard firmware can handle stabilization time, to avoid machine inertias ?

Thanks !!!

**Comment by arthurwolf** [comment]
What do you mean by stabilization time ?

On Mon, Nov 23, 2015 at 12:03 PM, valpoder <notifications@github.com> wrote:

> Good day:
>
> Small question, does smothieboard firmware can handle stabilization time,
> to avoid machine inertias ?
>
> Thanks !!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/776>.
>



-- 
Courage et bonne humeur.
