### ISSUE TITLE
Unused analog lines should be grounded on LPC1768-based hardware

### ISSUE THREAD

**Issue by bgamari** [Smoothieware/Smoothieware#80]
The LPC1768 has a notoriously unstable ADC. The mbed community has had a [bit](http://mbed.org/forum/bugs-suggestions/topic/1514/?page=2#comment-7783) of [experience](http://mbed.org/forum/mbed/topic/1866/) dealing with this and have a few [tricks](http://mbed.org/users/chris/notebook/Getting-best-ADC-performance/) to mitigate the problem. In addition to digital filtering (which we already do), they recommend that any unused analog inputs are grounded. An easy way to do this is to configure them as digital outputs and drive them low. It may be a good idea for Smoothie to do this, although it's unclear how this can be achieved in a hardware-independent manner.
## References
- http://tech.groups.yahoo.com/group/lpc2000/message/56239
- http://mbed.org/forum/bugs-suggestions/topic/1514/?page=2#comment-7783
- http://mbed.org/forum/mbed/topic/1866/
- http://gvworks.blogspot.com/2011/03/lpc1768-adc-has-too-many-glitches.html
- http://mbed.org/users/chris/notebook/Getting-best-ADC-performance/

**Comment by wolfmanjm** [comment]
Additionally with a LPCExpresso you are not using the AVCC and AGND which also introduces noise. Smoothieboard does use AVCC.
I recently added some extra filtering and low pass filtering which does help a lot.

**Comment by wolfmanjm** [comment]
this is a hardware issue and should be in the repo for the hardware.
