### ISSUE TITLE
temp module event no trigger unless threshold is crossed

### ISSUE THREAD

**Issue by dposea** [Smoothieware/Smoothieware#809]
if you define a switch.fan , but the hotend is above the trigger termp when the printer is powered up, the event never get triggered and the fan stays off.

**Comment by wolfmanjm** [comment]
Are you using the very latest edge?

**Comment by wolfmanjm** [comment]
Please provide your config.

**Comment by wolfmanjm** [comment]
I cannot reproduce,I think this was fixed several weeks ago.
So either you are not using the latest edge, or your config is not setup properly.

**Comment by dposea** [comment]
I'm using the version suggested by the docs on turning of the microSD card.

https://github.com/Smoothieware/Smoothieware/blob/edge/FirmwareBin/firmware-disablemsd.bin?raw=true. I noticed there are menu changes too.

**Comment by dposea** [comment]
I just noticed the no msd version is also in firmware.bin. I'll test on that version just to be sure, but will not post again unless there is stil a problem.

**Comment by wolfmanjm** [comment]
use the posted firmware.bin or build the latest version. this is NOT a bug I tested it.
