### ISSUE TITLE
Jogging after print aborted from Smoothie Web causes erroneous movment 

### ISSUE THREAD

**Issue by W3DRK** [Smoothieware/Smoothieware#818]
I've noticed that from within Smoothie Web if I abort a print and then use the jog controls to lift the Z axis or move X/Y, the first move after the abort will cause a random and often violent move of X or Y.

For example: During a print in progress, if I click the Abort button in Smoothie Web, once the printer stops if I lift click the jog control to lift the Z axis, X or Y will move as well, and usually a LOT faster than Z.  Many times the random move results in X or Y slamming into their mechanical limits, grinding stepper sounds, etc...potentially damaging behavior.

This only happens during the first move after using Smoothie Web to abort a print.  And the the jog commands can come from Smoothie Web, USB, wherever..the result is the same.  

Any moves after that work normally, assuming the erroneous move didn't hit the limit switch which requires an M999 or reset to recover from.

There is at least one other individual who has reported the same behavior in the Smoothieware forum, so it does not appear to be isolated to just me.

I have also noticed that many times, uploading a file in Smoothie Web makes the Z Axis move.  It occurs as soon as I click the upload button...the Z Axis will move up 10mm or so.

Build version: edge-10ee205, Build date: Jan  3 2016 04:05:28

**Comment by wolfmanjm** [comment]
delta or cartesian? printing from sdcard? auto levelling enabled?

**Comment by Mikk36** [comment]
Are the motors disabled after the abort by any chance?
If so, you should see the exact same behaviour without even aborting.

**Comment by W3DRK** [comment]
Excellent questions, I should have provided these from the start.

It's a dual Z cartesian (Ord Bot Hadron) and I'm printing from the on-board SD card.  No auto bed leveling enabled.  I'm attaching my config below if it helps.

I believe it leaves the motors enabled after I abort it but I will double check tonight.  But it only happens on the very first move after aborting.  Any subsequent moves after that work normally, assuming it didn't slam one of the axis' into a limit switch and halt all movement.



> cat sd/config.txt
# NOTE Lines must not exceed 132 characters
# Robot module configurations : general handling of movement G-codes and slicing into moves
default_feed_rate                            4000             # Default rate ( mm/minute ) for G1/G2/G3 moves
default_seek_rate                            4000             # Default rate ( mm/minute ) for G0 moves
mm_per_arc_segment                           0.5              # Arcs are cut into segments ( lines ), this is the length for
                                                              # these segments.  Smaller values mean more resolution,
                                                              # higher values mean faster computation
#mm_per_line_segment                          5               # Lines can be cut into segments ( not usefull with cartesian
                                                              # coordinates robots ).

# Arm solution configuration : Cartesian robot. Translates mm positions into stepper positions

# 1/32 microsteps
alpha_steps_per_mm                           161.1047            # Steps per mm for alpha stepper (X)
beta_steps_per_mm                            161.1047            # Steps per mm for beta stepper  (Y)
gamma_steps_per_mm                           811.2               # Steps per mm for gamma stepper (Z)


# Planner module configuration : Look-ahead and acceleration configuration
planner_queue_size                           32               # DO NOT CHANGE THIS UNLESS YOU KNOW EXACTLY WHAT YOU ARE DOING
acceleration                                 3000             # Acceleration in mm/second/second.
#z_acceleration                              500              # Acceleration for Z only moves in mm/s^2, 0 uses acceleration which is the default. DO NOT SET ON A DELTA
acceleration_ticks_per_second                1000             # Number of times per second the speed is updated
junction_deviation                           0.02             # Similar to the old "max_jerk", in millimeters,
                                                              # see https://github.com/grbl/grbl/blob/master/planner.c
                                                              # and https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.8
                                                              # Lower values mean being more careful, higher values means being
                                                              # faster and have more jerk
#z_junction_deviation                        0.0              # for Z only moves, -1 uses junction_deviation, zero disables junction_deviation on z moves DO NOT SET ON A DELTA
#minimum_planner_speed                       0.0              # sets the minimum planner speed in mm/sec

# Stepper module configuration
microseconds_per_step_pulse                  1                # Duration of step pulses to stepper drivers, in microseconds
base_stepping_frequency                      100000           # Base frequency for stepping

# Cartesian axis speed limits
x_axis_max_speed                             18000            # mm/min
y_axis_max_speed                             18000            # mm/min
z_axis_max_speed                             600              # mm/min

# Stepper module pins ( ports, and pin numbers, appending "!" to the number will invert a pin )
alpha_step_pin                               2.0              # Pin for alpha stepper step signal
alpha_dir_pin                                0.5!             # Pin for alpha stepper direction
alpha_en_pin                                 0.4              # Pin for alpha enable pin
alpha_current                                1.2              # X stepper motor current
alpha_max_rate                               30000.0          # mm/min

beta_step_pin                                2.1              # Pin for beta stepper step signal
beta_dir_pin                                 0.11             # Pin for beta stepper direction
beta_en_pin                                  0.10             # Pin for beta enable
beta_current                                 1.2              # Y stepper motor current
beta_max_rate                                30000.0          # mm/min

gamma_step_pin                               2.2              # Pin for gamma stepper step signal
gamma_dir_pin                                0.20!             # Pin for gamma stepper direction
gamma_en_pin                                 0.19             # Pin for gamma enable
gamma_current                                1.2              # Z stepper motor current
epsilon_current                              1.2              # Second Z stepper motor current
gamma_max_rate                               300.0            # mm/min



# Serial communications configuration ( baud rate default to 9600 if undefined )
uart0.baud_rate                              115200           # Baud rate for the default hardware serial port
second_usb_serial_enable                     false            # This enables a second usb serial port (to have both pronterface
                                                              # and a terminal connected)
#leds_disable                                true             # disable using leds after config loaded
#play_led_disable                            true             # disable the play led

# kill button (used to be called pause) maybe assigned to a different pin, set to the onboard pin by default
kill_button_enable                           true             # set to true to enable a kill button
kill_button_pin                              2.12             # kill button pin. default is same as pause button 2.12 (2.11 is another good choice)

#msd_disable                                 false            # disable the MSD (USB SDCARD) when set to true (needs special binary)
#dfu_enable                                  false            # for linux developers, set to true to enable DFU
#watchdog_timeout                            10               # watchdog timeout in seconds, default is 10, set to 0 to disable the watchdog

# Extruder module configuration

extruder.hotend.enable                          true             # Whether to activate the extruder module at all. All configuration is ignored if false
# extruder.hotend.steps_per_mm                  147.575          # (1/16 microsteps) Steps per mm for extruder stepper
extruder.hotend.steps_per_mm                    295.15           # (1/32 microsteps) Steps per mm for extruder stepper
extruder.hotend.default_feed_rate               600              # Default rate ( mm/minute ) for moves where only the extruder moves
extruder.hotend.acceleration                    3600             # Acceleration for the stepper motor mm/secÂ²
extruder.hotend.max_speed                       160              # mm/s
extruder.hotend.step_pin                        2.3              # Pin for extruder step signal
extruder.hotend.dir_pin                         0.22!            # Pin for extruder dir signal
extruder.hotend.en_pin                          0.21             # Pin for extruder enable signal

# firmware retract settings when using G10/G11, these are the defaults if not defined, must be defined for each extruder if not using the defaults
extruder.hotend.retract_length                  3.5             # retract length in mm
extruder.hotend.retract_feedrate                100             # retract feedrate in mm/sec
extruder.hotend.retract_recover_length          0               # additional length for recover
extruder.hotend.retract_recover_feedrate        40              # recover feedrate in mm/sec (should be less than retract feedrate)
extruder.hotend.retract_zlift_length            .2              # zlift on retract in mm, 0 disables
extruder.hotend.retract_zlift_feedrate          12000           # zlift feedrate in mm/min (Note mm/min NOT mm/sec)

delta_current                                           1.2             # Extruder stepper motor current

# Laser module configuration
laser_module_enable                          false            # Whether to activate the laser module at all. All configuration is

# Hotend temperature control configuration
temperature_control.hotend.enable            true             # Whether to activate this ( "hotend" ) module at all.
                                                              # All configuration is ignored if false.
temperature_control.hotend.thermistor_pin    0.23             # Pin for the thermistor to read
temperature_control.hotend.heater_pin        2.7              # Pin that controls the heater, set to nc if a readonly thermistor is being defined
temperature_control.hotend.thermistor        SEMITEC          # see http://smoothieware.org/temperaturecontrol#toc5SEMITEC
#temperature_control.hotend.beta             4066             # or set the beta value
temperature_control.hotend.set_m_code        104              #
temperature_control.hotend.set_and_wait_m_code 109            #
temperature_control.hotend.designator        T                #
temperature_control.hotend.max_temp          280              # Set maximum temperature - Will prevent heating above 300 by default
#temperature_control.hotend.min_temp         0                # Set minimum temperature - Will prevent heating below if set

temperature_control.hotend.p_factor         35.8             # permanently set the PID values after an auto pid
temperature_control.hotend.i_factor         2.784            #
temperature_control.hotend.d_factor         115              #

#temperature_control.hotend.max_pwm          64               # max pwm, 64 is a good value if driving a 12v resistor with 24v.

temperature_control.bed.enable               true             #
temperature_control.bed.thermistor_pin       0.24             #
temperature_control.bed.heater_pin           2.5              #
temperature_control.bed.thermistor           EPCOS100K        # see http://smoothieware.org/temperaturecontrol#toc5
#temperature_control.bed.beta                4066             # or set the beta value

temperature_control.bed.set_m_code           140              #
temperature_control.bed.set_and_wait_m_code  190              #
temperature_control.bed.designator           B                #

temperature_control.bed.p_factor                35.3143          # permanently set the PID values after an auto pid
temperature_control.bed.i_factor                1.9457           #
temperature_control.bed.d_factor                160.2387         #


temperature_control.bed.bang_bang            false           # set to true to use bang bang control rather than PID
temperature_control.bed.hysteresis           0.5             # set to the temperature in degrees C to use as hysteresis
                                                              # when using bang bang

# Switch module for fan control
switch.fan.enable                            true             #
switch.fan.input_on_command                  M106             #
switch.fan.input_off_command                 M107             #
switch.fan.output_pin                        2.6              #
switch.fan.output_type                       pwm              # pwm output settable with S parameter in the input_on_comand
#switch.fan.max_pwm                           255              # set max pwm for the pin default is 255

#switch.misc.enable                           true             #
#switch.misc.input_on_command                 M42              #
#switch.misc.input_off_command                M43              #
#switch.misc.output_pin                       2.4              #
#switch.misc.output_type                      digital          # just an on or off pin

# automatically toggle a switch at a specified temperature. Different ones of these may be defined to monitor different temperatures and switch different swithxes
# useful to turn on a fan or water pump to cool the hotend
#temperatureswitch.hotend.enable              true             #
#temperatureswitch.hotend.designator          T                # first character of the temperature control designator to use as the temperature sensor to monitor
#temperatureswitch.hotend.switch              misc             # select which switch to use, matches the name of the defined switch
#temperatureswitch.hotend.threshold_temp      60.0             # temperature to turn on (if rising) or off the switch
#temperatureswitch.hotend.heatup_poll         15               # poll heatup at 15 sec intervals
#temperatureswitch.hotend.cooldown_poll       60               # poll cooldown at 60 sec intervals

# Switch module for spindle control
#switch.spindle.enable                        false            #

# Endstops
endstops_enable                              true             # the endstop module is enabled by default and can be disabled here
alpha_min_endstop                            1.24^            # add a ! to invert if endstop is NO connected to ground
alpha_max_endstop                            nc                   # NOTE set to nc if this is not installed
alpha_homing_direction                       home_to_min      # or set to home_to_max and set alpha_max
alpha_min                                    0                # this gets loaded after homing when home_to_min is set
alpha_max                                    180              # this gets loaded after homing when home_to_max is set
beta_min_endstop                             1.26^            #
beta_max_endstop                             nc               #
beta_homing_direction                        home_to_min      #
beta_min                                     0                #
beta_max                                     180              #
gamma_min_endstop                            1.28^            #
gamma_max_endstop                            nc               #
gamma_homing_direction                       home_to_min      #
gamma_min                                    0                #
gamma_max                                    180              #

# optional order in which axis will home, default is they all home at the same time,
# if this is set it will force each axis to home one at a time in the specified order
#homing_order                                 XYZ              # x axis followed by y then z last

# optional enable limit switches, actions will stop if any enabled limit switch is triggered
alpha_limit_enable                          true            # set to true to enable X min and max limit switches
beta_limit_enable                           true            # set to true to enable Y min and max limit switches
gamma_limit_enable                          false                       # set to true to enable Z min and max limit switches

alpha_fast_homing_rate_mm_s                  50               # feedrates in mm/second
beta_fast_homing_rate_mm_s                   50               # "
gamma_fast_homing_rate_mm_s                  4                # "
alpha_slow_homing_rate_mm_s                  25               # "
beta_slow_homing_rate_mm_s                   25               # "
gamma_slow_homing_rate_mm_s                  2                # "

alpha_homing_retract_mm                      5                # distance in mm
beta_homing_retract_mm                       5                # "
gamma_homing_retract_mm                      0                # "

#endstop_debounce_count                       100              # uncomment if you get noise on your endstops, default is 100

# optional Z probe
zprobe.enable                                false           # set to true to enable a zprobe
zprobe.probe_pin                             1.28!^          # pin probe is attached to if NC remove the !
zprobe.slow_feedrate                         5               # mm/sec probe feed rate
#zprobe.debounce_count                       100             # set if noisy
zprobe.fast_feedrate                         100             # move feedrate mm/sec
zprobe.probe_height                          5               # how much above bed to start probe
#gamma_min_endstop                           nc              # normally 1.28. Change to nc to prevent conflict,

# associated with zprobe the leveling strategy to use
#leveling-strategy.three-point-leveling.enable         true        # a leveling strategy that probes three points to define a plane and keeps the Z parallel to that plane
#leveling-strategy.three-point-leveling.point1         100.0,0.0   # the first probe point (x,y) optional may be defined with M557
#leveling-strategy.three-point-leveling.point2         200.0,200.0 # the second probe point (x,y)
#leveling-strategy.three-point-leveling.point3         0.0,200.0   # the third probe point (x,y)
#leveling-strategy.three-point-leveling.home_first     true        # home the XY axis before probing
#leveling-strategy.three-point-leveling.tolerance      0.03        # the probe tolerance in mm, anything less that this will be ignored, default is 0.03mm
#leveling-strategy.three-point-leveling.probe_offsets  0,0,0       # the probe offsets from nozzle, must be x,y,z, default is no offset
#leveling-strategy.three-point-leveling.save_plane     false       # set to true to allow the bed plane to be saved with M500 default is false

# Panel
panel.enable                                  true              # set to true to enable the panel code
panel.lcd                                   reprap_discount_glcd     #
panel.spi_channel                           0                 # spi channel to use  ; GLCD EXP1 Pins 3,5 (MOSI, SCLK)
panel.spi_cs_pin                            0.16              # spi chip select     ; GLCD EXP1 Pin 4
panel.encoder_a_pin                         3.26!^            # encoder pin         ; GLCD EXP2 Pin 3
panel.encoder_b_pin                         3.25!^            # encoder pin         ; GLCD EXP2 Pin 5
panel.click_button_pin                      1.30!^            # click button        ; GLCD EXP1 Pin 2
panel.buzz_pin                              1.31              # pin for buzzer      ; GLCD EXP1 Pin 1
panel.back_button_pin                       2.11!^            # back button         ; GLCD EXP2 Pin 8
panel.external_sd                                   true              # set to true if there is an extrernal sdcard on the panel
panel.external_sd.spi_channel               1                 # set spi channel the sdcard is on
panel.external_sd.spi_cs_pin                0.28              # set spi chip select for the sdcard (or any spare pin)
panel.external_sd.sdcd_pin                  0.27!^            # sd detect signal (set to nc if no sdcard detect) (or any spare pin)

panel.menu_offset                            1                 # some panels will need 1 here

panel.alpha_jog_feedrate                     6000              # x jogging feedrate in mm/min
panel.beta_jog_feedrate                      6000              # y jogging feedrate in mm/min
panel.gamma_jog_feedrate                     200               # z jogging feedrate in mm/min

panel.hotend_temperature                     185               # temp to set hotend when preheat is selected
panel.bed_temperature                        60                # temp to set bed when preheat is selected

# Example of a custom menu entry, which will show up in the Custom entry.
# NOTE _ gets converted to space in the menu and commands, | is used to separate multiple commands
custom_menu.power_on.enable                true              #
custom_menu.power_on.name                  Power_on          #
custom_menu.power_on.command               M80               #

custom_menu.power_off.enable               true              #
custom_menu.power_off.name                 Power_off         #
custom_menu.power_off.command              M81               #

# Only needed on a smoothieboard
currentcontrol_module_enable                 true             #

return_error_on_unhandled_gcode              false            #

# network settings
network.enable                               true             # enable the ethernet network services
network.webserver.enable                     true             # enable the webserver
network.telnet.enable                        true             # enable the telnet server
#network.ip_address                          auto             # use dhcp to get ip address
# uncomment the 3 below to manually setup ip address
network.ip_address                           192.168.1.10     # the IP address
network.ip_mask                              255.255.255.0    # the ip mask
network.ip_gateway                           192.168.1.1      # the gateway address
network.hostname                                                         smoothie         # optionally set this hostname for dhcp
#network.mac_override                        xx.xx.xx.xx.xx.xx  # override the mac address, only do this if you have a conflict

**Comment by wolfmanjm** [comment]
FYI the abort command never guarantees the position is correct, and homing is always recommended after you use the abort command, as it is really hard to recover the actual position of the actuators after you force the queued commands to abort. It is a lot safer to pause and let the queue drain.

**Comment by wolfmanjm** [comment]
What board are you using? as smoothieboards do not have 1/32 and the config is not an azteeg X5.

**Comment by W3DRK** [comment]
I wanted 1/32 micro stepping so I went with an SBASE.  I also donated to Smoothieware.  In any event I can't imagine it being a hardware issue...

There is a problem with homing after an abort, at least in my case.  If there's a half-printed object stuck to the glass, obviously bad things are going to happen if I try to home the printer.  

Generally my workflow is if I need to abort a print for whatever reason, I click abort, then click to lift Z 10mm-20mm to lift the hot nozzle off the print, then shut off the motors so I can slide the Y axis out and wait for the print to cool so it can be removed from the glass.  I can't manually lift Z since it's on lead screws.

Instead of aborting, you suggest pausing?  I don't recall seeing a pause option in Smoothie Web but I may just be overlooking that.  It doesn't seem to only be a loss of positioning issue, the speed in which these random movements occur can be EXTREMELY fast and violent.  Further, why would instructing Z to move 10mm cause X or Y to go slam into its mechanical limits?  No mater were Smoothie thinks the axis are, I can't imagine 2 axis moving simultaneously when only one was instructed to do so.

Another thing to note, if I tell Z to lift only .1mm, the corresponding X or Y move will likely not be far enough to hit anything.  But if I lift Z 1mm or 10mm, that's when things get scary.  It almost seems as if those moves are a multiple of the Z move, or somehow getting the higher steps/mm needed for the Z lead screws.

**Comment by wolfmanjm** [comment]
I have confirmed that abort is not calculating the correct current position, so I suggest using either abort 1 command or M25 which will pause the print once the queue is empty.

I'm not sure how long it will take to fix this issue. But I'm lookin ginto it.

Thanks

**Comment by wolfmanjm** [comment]
ok seems I fixed this a long time ago, then unfixed it recently because I forgot why I fixed it originally :)

**Comment by wolfmanjm** [comment]
@W3DRK please test this when you get a chance and confirm it is fixed. I still recommend homing after an abort though.

**Comment by W3DRK** [comment]
Great!  So edge-fc8cfc6 should have the fix reapplied?  I will try and report back shortly...

**Comment by wolfmanjm** [comment]
No you will need to build latest edge cbbd33b1e3eab0e19f4ad20f63ad8d090deb68c4
the firmware.bin is a few weeks old

**Comment by W3DRK** [comment]
Yep I figured that out a few seconds after I asked. Thanks!

**Comment by jjcolletta** [comment]
W3DRK - Thanks for submitting this and Wolf thanks for the fix (re-fix) fix.  I thought I was loosing my mind.  I will use the pause command and not the abort button on the web or from the GLCD for awhile.

**Comment by W3DRK** [comment]
Cool, I'm testing cbbd33b now and will report back in a few minutes as to whether or not it takes care of it.

**Comment by W3DRK** [comment]
OK the problem appears to be gone!
