### ISSUE TITLE
Refactor : Remove on_gcode_execute

### ISSUE THREAD

**Issue by arthurwolf** [Smoothieware/Smoothieware#82]
Planned refactor.

We would stop storing gcodes amongst with blocks. Instead, modules would read gcodes in on_gcode_received, transform those into a ModuleData storage thingie, that would be attached to blocks.

class ModuleData { Module* owner; }; .... class TemperatureControlBlob : public ModuleData { ... }; .... class Block { ... vector or whatever <ModuleData*> data; }

**Comment by wolfmanjm** [comment]
done
