### ISSUE TITLE
connecting to Octoprint

### ISSUE THREAD

**Issue by wildcardfox** [Smoothieware/Smoothieware#826]
Hi, I have recently switch to Smoothieware, a Smoothieboard X5, and I have been unable to connect to Octoprint. I've tried the safe method on this page https://github.com/foosel/OctoPrint/wiki/Setup-OctoPrint-with-Smoothie, and when I try to save text into SmoothieUpload.sh I get an error that Directory or file does not exist. 

I've also tired http://smoothieware.org/octoprint

and I get "bash" incorrect. Can someone please let me know what I'm doing wrong, or possibly walk me through the setup to get the Smoothieware running on Octoprint...

Thanks

-Brett

**Comment by wolfmanjm** [comment]
issues are for reporting bugs. this is not a bug. As for using octoprint I suggest you try their documents.
there is an octoprint IRC channel #octoprint, I suggest you ask there.
Thanks
