### ISSUE TITLE
Code wont compile

### ISSUE THREAD

**Issue by DarkBlaez** [Smoothieware/Smoothieware#843]
Code errors out on a "make clean all"

Compiling modules/robot/Feedback.cpp
modules/robot/Feedback.cpp:17:33: fatal error: modules/robot/robot.h: No such file or directory
 #include "modules/robot/robot.h"

Looks like modules directory is incomplete

**Comment by arthurwolf** [comment]
is the file present ?

On Wed, Feb 10, 2016 at 8:55 PM, DarkBlaez <notifications@github.com> wrote:

> Code errors out on a "make clean all"
>
> Compiling modules/robot/Feedback.cpp
> modules/robot/Feedback.cpp:17:33: fatal error: modules/robot/robot.h: No
> such file or directory
> #include "modules/robot/robot.h"
>
> Looks like modules directory is incomplete
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/843>.
>



-- 
Courage et bonne humeur.

**Comment by wolfmanjm** [comment]
There is no modules/robot/Feedback.cpp in smoothie, so I suggest you get a copy of smoothie not som eother branch or fork.
