### ISSUE TITLE
best motor_driver_control SPI channel?

### ISSUE THREAD

**Issue by greyltc** [Smoothieware/Smoothieware#889]
I'm having a look at [MotorDriverControl.cpp](https://github.com/Smoothieware/Smoothieware/blob/edge/src/modules/utils/motordrivercontrol/MotorDriverControl.cpp) to try to teach myself how to get my DRV8711 working as a driver for extruder.hotend. 

I'm also using a max31855 in my machine to read my bed temperature. I've read (https://github.com/Smoothieware/Smoothieware/issues/711) that sharing the SPI_1 bus between the SD card and that thermocouple IC is a no-no, so currently I'm using SPI_0 for my thermocouple ADC.

What channel should I use for talking with my DRV8711? Would the max31855 comms on SPI_0 clobber my DRV8711 comms? Do I risk corrupting my SD card if I share SPI_1?

I'm not using USB in case that matters here.

**Comment by wolfmanjm** [comment]
You must use the only SPI available, you cannot share it.
