### ISSUE TITLE
the current sense resistor value in motor_driver_control for DRV8711 seems to be hard coded

### ISSUE THREAD

**Issue by greyltc** [Smoothieware/Smoothieware#890]
Is there anything I can put into my config file to tell my smoothieboard what value to use for the current sense resistor when using the motor_driver_control module with a DRV8711?

Is it hard coded to be 50mOhm [here] (https://github.com/Smoothieware/Smoothieware/blob/467c3642c15958c96aa96062feaa7172a079c507/src/modules/utils/motordrivercontrol/drivers/DRV8711/drv8711.h#L142)?

The sense resistor I have is 33mOhm. So maybe as a temporary workaround to this I could scale the `current` setting in my config file by 33/50 = 0.66?

**Comment by wolfmanjm** [comment]
it is hard coded. That should be fixed.

**Comment by wolfmanjm** [comment]
fixed in #897

**Comment by greyltc** [comment]
Thanks!
