### ISSUE TITLE
Panel displays incorrect position after G92

### ISSUE THREAD

**Issue by CapnBry** [Smoothieware/Smoothieware#893]
I've noticed that sometime in December timeframe the panel LCD display started showing incorrect values for my Z axis. It looks like there were some internal changes made to how G92 position adjustments are used and these values are not used to calculate the position displayed on the panel. This may be for every axis but I only use G92 to calibrate my Z offset.

* Home Z axis: `G28 Z0`
* LCD Panel shows Z0.00. M114 reports Z0.00
* Enter a G92 value: `G92 Z1.0`
* LCD Panel still shows Z0.00. M114 reports proper Z1.00

Note that the robot works as expected, just the LCD display doesn't display the right value.

**Comment by wolfmanjm** [comment]
fixed in PR #898 

TODO still need to make it an option to display machine coordinates.

**Comment by CapnBry** [comment]
Confirmed, working great now, thanks!
