### ISSUE TITLE
Disconnected thermistors return "inf" via M105

### ISSUE THREAD

**Issue by orcinus** [Smoothieware/Smoothieware#90]
It makes sense as a way of signaling something is wrong, but unfortunately, clients like Pronterface choke on it. 

Pronterface in particular tries to convert it into integer and errors out trying to refresh the temperature widgets (causing slight weirdness in Windows and major UI weirdness on Mac).

**Comment by wolfmanjm** [comment]
I'd say that is a bug in the host

**Comment by orcinus** [comment]
"inf" is really not a very valid integer nor float, so no, i'd say it's a bug in the firmware ;)
It's a rather old bug report, though, not sure if it's still there in the first place.

**Comment by wolfmanjm** [comment]
FYI inf is a valid floating point number, it denotes infinity, which is supported by most if not all compiter languages. in c and c++ it is isinf().

It is the ONLY way to denote an invalid floating number.

**Comment by orcinus** [comment]
"inf" is a valid *representation* of a floating point number, used by a programming language, as an *exception*. In and of itself it has no meaning as a float. It does not exist outside that context.
You could just as easily claim NaN is a valid float, which would make no sense, would it?

You can't apply language construct rules to an output of a program.

Otherwise one could, by a stretch, also claim an exception or a warning or an error were "a valid floating point number".

**Comment by orcinus** [comment]
(It could be argued, though, that host programs - and 3D printer firmwares by extension - do not have a clearly defined standard of communicating invalid numbers. In that context, you are right, it is a host matter.)

**Comment by orcinus** [comment]
FWIW, convention - in Marlin and Repetier, at least - seems to be to report a MINTEMP and MAXTEMP error for out of bounds temperatures.
