### ISSUE TITLE
Pid autotune not working with second_usb_serial_enable set to true    

### ISSUE THREAD

**Issue by droncal** [Smoothieware/Smoothieware#923]
Hello, I downloaded the last firmware.bin from github repository and I put it on my Smoothieware 5xc and then I downloaded the default config too. 

In this config I set : 
second_usb_serial_enable    true

Then, when I try and autotune the smoothie crashes... They told me to open here an issue but if anybody had this problem tell me. Thank you.

**Comment by wolfmanjm** [comment]
Probably a config error.

**Comment by dcousens** [comment]
>  smoothie crashes

A config error causes a crash?  What?
