### ISSUE TITLE
Maximum speeds not checked when moving axes from the internal web interface

### ISSUE THREAD

**Issue by dethegeek** [Smoothieware/Smoothieware#924]
Hi

I'm setting up my printer with the smoothieboard.

I noticed that I can move X axis at higher speed that the speed limit defined in the config file.

Is it a wanted behavior ?

**Comment by arthurwolf** [comment]
There is no reason why this would happen. How did you specify the movement
speed, and your maximum speed ?

On Mon, May 16, 2016 at 8:04 PM, dethegeek <notifications@github.com> wrote:

> Hi
>
> I'm setting up my printer with the smoothieboard.
>
> I noticed that I can move X axis at higher speed that the speed limit
> defined in the config file.
>
> Is it a wanted behavior ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/924>
>



-- 
Courage et bonne humeur.

**Comment by wolfmanjm** [comment]
Jogging speed is limited by whatever is set in M203. This works. I suspect you have either the config-overide set or the config is wrong.
Check M203 with M503 see what you have it set to.

**Comment by dethegeek** [comment]
I think I have to understand the difference between x_axis_max_speed and  alpha_max_rate

Setting my speed limit in x_axis_max_speed solved the issue.

what is the diference between max_rate and max_speed ?

**Comment by dcousens** [comment]
@dethegeek at a guess, you could probably put `x_axis_max_speed` at close to infinity, and instead just limit the `alpha_max_rate`?
Relevant file seems to be Smoothieware/src/modules/robot/Robot.cpp

**Comment by dethegeek** [comment]
@dcousens 

x_axis_max_speed was 30000 and alpha_max_rate 12000

The issue has been solved by setting x_axis_max_speed to 12000 too

My understanding of the code you mention seems confirm these new settings. However, I don't deduce setting x_axis_max_speed no a near infinite value is a good choice.
