### ISSUE TITLE
Smoothieboard Emulator or how to run firmware without owning a board?

### ISSUE THREAD

**Issue by SimplyAhmazing** [Smoothieware/Smoothieware#928]
If I don't own a Smoothieboard, is it possible to run the Smoothieware firmware code on an emulator or to somehow get it up and running and be able to interact with it in regards to sending g-code via a serial interface?

Or do you have to own a physical Smoothieboard? I suppose I can wait until next week to get access to one.

Thanks

**Comment by wolfmanjm** [comment]
no. You would need to write one.

**Comment by Harvie** [comment]
I develop g-code sender and i don't have smoothieboard to test it. Also i want to run automatic checks in Travis CI. Can you please write such emulator to make implementing of smoothie support easier?
