### ISSUE TITLE
Minimum actuator rate is hardcoded

### ISSUE THREAD

**Issue by dutchrazor** [Smoothieware/Smoothieware#936]
I saw something interesting in StepperMotor.cpp:

"
// in steps/sec the default minimum speed (was 20steps/sec hardcoded)
float StepperMotor::default_minimum_actuator_rate=  20.0F;
"

I set it to 1.0 since I wanted to move a high step-rate axis slowly, and it seems to work. Is there still a reason this is hardcoded?

Best regards,

Fabien

**Comment by triffid** [comment]
Yes, some slicers issue moves with F0 and we get frequent complaints that
smoothie locks up as a result. Feel free to keep this change in your
private fork and rebase as necessary if it works well for you :)

**Comment by wolfmanjm** [comment]
yea but this is no longer used in the upcoming tick generator rewrite.

**Comment by dutchrazor** [comment]
Ah thanks for the explanation. Is there any ETA on the tick generator rewrite?

I stumbled into this because I hooked up a printhead which required longer pulses than the normal stepper motor pulses (longer than desired for the XYZ axis), so I wrote in a little hack to unstep the pulse of one of the extruder axes every x'th unstep pulse.
