### ISSUE TITLE
Resume goes to negative Z ( bug)

### ISSUE THREAD

**Issue by karabas** [Smoothieware/Smoothieware#937]
I am trying custom menu suspend/resume
after_suspend_gcode     G91|G1_E-2|G1_Z10_F3000|G90|G1_X-50_Y-50     
before_resume_gcode   G91|G1_E-0.2|G1_Z-10_F3000|G1_F1800|G90      
(or before_resume_gcode   G91|G1_E-0.2|G1_F1800|G90   the same result)

after resuming inside layer head goes below printing level for  about 1-2mm and prints until next layer start, then all perfect.

If I suspend on the 2-nd or 3d layer, head tryes to print below glass.

**Comment by wolfmanjm** [comment]
resume restores the last position it was printing at, when suspend is executed, and before the after_suspend_gcode, so your before_resume is irrelevant and incorrect. this is documented in the wiki.
