### ISSUE TITLE
Smoothie Master - Stable, most tested url opens Nightly Builds page

### ISSUE THREAD

**Issue by dintid** [Smoothieware/Smoothieware#940]
Sorry if posted wrong. Don't know where to post such issues?

When clicking the "**Smoothie Master - Stable, most tested**" url, which does point at "http://triffid-hunter.no-ip.info/Smoothie-master.html" it opens a page with the headline "**Smoothie-master Nightly Builds**"

Guess something is wrong here?

**Build guide**
Is there a build and edit guide to the firmware? I HAVE read somewhere you should run MAKE in a raised command, but I can't find any info aside from that... no guide somewhere?

**Comment by wolfmanjm** [comment]
it is all documented in the wiki. please do not ask questions as an issue this is for bug reporting not questions. the wiki has a community link with many options for asking questions. thank you
