### ISSUE TITLE
Limit Switches not working as expected

### ISSUE THREAD

**Issue by Zaaphod** [Smoothieware/Smoothieware#947]
The limit switches do not work the way I expect them to work on smoothie.   They allow you to move toward a switch that is already activated after doing an M999 command... and that should never happen. 

Test to duplicate the problem
G1 X1000    ;Move X some distance that will hit a limit switch
as expected I get: Limit switch X Max hit, reset or M999
M999           ;reset from halted state
now.. at this point, my X axis is still hitting the Max limit switch
G1 X1100    ;yes, I know I shouldn't be moving in that direction, but that's irrelevant. 
Machine now moves completely into the limit switch... It should not have moved, it should have instantly given me the above error.

In order to get smoothie to respond to the limit switch again, I need to move off of it first, then if I hit it again it will activate.. even if I hit it before the move, it will still activate.. this is correct.

After hitting any limit switch, after the M999,  it should only allow movement in the opposite direction, if a move is attempted in the direction a switch is already hit, there should be no motion attempted and the same limit switch error should be output.

I have no idea where limit switches are processed in the code but It's acting as if it only senses the transition from an non-limit condition to a limit condition.. if it's already in a limit condition it does not see anything.. it's as if it's edge triggered, but limit switches should not be edge triggered, they should be absolute.  If the switch is in a limit condition, no motion should ever be attempted in that direction under any circumstance, regardless of the previous state of the limit switch. 

The reason I think it's edge triggering is because if I hit the switch during a move, the machine stops with an error, I then issue M999.  If I then remove the limit condition, then apply it again before attempting a move, It will then correctly give me the immediate error.  If I do not remove the limit signal then apply it again and the limit is still just being held because the machine is on the switch, then it moves the complete distance and in fact ignores the fact that the switch is in a limit condition indefinitely until the limit condition is removed.. only then will it respond to a new limit condition

Edit:  I also noticed another issue related to limit switches, so I'll include it here.  
If you are moving in say a positive direction and manually activate the min limit switch, it stops the machine, but it should not..   That's not the direction we are trying to go and the state of that limit switch is irrelevant.   If I did hit the negative switch by moving negative too far, then I need to be able to move positive to get off the switch... at the moment I could move either direction because M999 makes it ignore limit switches altogether until they are released then re-activated again, but this allows you to move further against the limit with no attempt to stop.. once that issue is fixed, this secondary issue will be a problem because you will then be stuck against the limit switch being unable to move in either direction.

Edit 2 
Upon further testing I discovered (by destroying one of my limit switches) that smoothie does not instantly stop upon hitting a limit switch.. instead limit switches initiate an immediate deceleration... this is not fast enough!  Defiantly without a doubt ALL Motion is to cease immediately upon receipt of a limit condition, but only in the direction of current travel. it's not a request, it's a hard stop NOW.  This behavior is completely incorrect and needs to be addressed.    It's never optional to move even one step upon receiving a limit condition. 

Edit 3
I think it might be disabling the motor drives to attempt an immediate stop.  This is great if you are using on board drivers, but not so good if you are using external drives and purposefully never wired drive enable..  the reason for not using it is because some of my spindles are very heavy and if you suddenly disable the Z axis they will drop like a rock.   Also when cutting with a high speed router or milling machine it's a BAD idea to suddenly disable stepper drives while the cutting tool is engaged in the material.. the continued rotation of the cutting tool can push things around, pull the Z axis further into the material or generally make a mess of things without the holding power of the stepper motors to keep things in place.   The best solution is to instantly stop sending steps... instantly stop moving, but HOLD your position.

**Comment by wolfmanjm** [comment]
I am sorry but this is the best we can do for now. If you want to rewrite the limit switch code please feel free to do so, and submit a PR. As this is an issue the core team  will not be addressing I will close it.
