### ISSUE TITLE
Feature Request: Multiple Z Axis

### ISSUE THREAD

**Issue by Zaaphod** [Smoothieware/Smoothieware#950]
Almost all of my CNC routers have two Z heads on them, some have three, and also my milling machines have Z axis control of the Quill, but also a second Z control on the Knee as well.  

I know smoothie supports 5 axis, but it's XYZ and 2 extruders.  I'm thinking it would not take too much to expand this to allow two Z axis instead of extruders, perhaps on the CNC build.  It's very similar, the only big difference being that Z axis has limit switches and extruders do not. 

you would never be moving more than one extruder at a time, the same is true for multiple Z heads, in fact the two Z axis could have their switches share an input because you are only moving one at a time.

I can possibly do this with hardware, using GPIO as 'Z Select' but it would be great if it was something smoothie could do.   All that really needs to be done is for some command to tell smoothie to use different pins for Z step and Z dir Z en Zmin, and Zmax much the way that multiple extruders must change which step and direction pins are doing the extruding... the only real difference is I want to do this to the Z axis, not extruders, this means the homing routine would need to home each Z axis separately as well 

I would be happy to help code and test this, but I'm not sure how to get started, if someone more familiar with this project could point me in the right direction, it would be very helpful.

I also do not know how exactly this should happen.  Is there some G or M code that can be used for 'head select'?  how are extruders selected?  I would think whatever method is used to select an extruder would be useful to select Z heads.

I understand this is probably another one of my special cases, but I think other people could benefit from it as well.

**Comment by arthurwolf** [comment]
I don't think this is something we'll be supporting in v1.
In v2, we'll have more space for new features, and it's imaginable to create a module that'd have the ability to change the pins of other modules. So you could use commands to change the step pins, and macros to contain those commands and make them easier to use ...

**Comment by Zaaphod** [comment]
It would be great to think about it for V2.  I've been thinking about this.. I think it would be more beneficial to a lot more people if there were 4 axis with limit switches., Typically W is used for the second Z head, but it could be any letter.   A 4th CNC axis with limit switches would not only allow for my second Z head options, but also 4 independent axis hot wire machines would be possible, as well as something like a rotary 'A' Axis on a milling table where homing it to zero degrees would be important..  Also things like machines with a 'C' axis to keep a knife tangential to the cut would also need a 4th axis that could home as well.

**Comment by wolfmanjm** [comment]
Other than the endstops/homing you can already do this, just configure your z as extruders, and use T0/T1 to select between them. As for the endstop that is not likely to happen in the main branch code.
