### ISSUE TITLE
Delta Printer: Edit Individual "arm_lentgh" for Each Axis??

### ISSUE THREAD

**Issue by xboxhacker** [Smoothieware/Smoothieware#963]
Is there a way to edit individual "arm_lentgh" for each tower?

Coming from RAMPS, it has this ability. It seems Smoothie only sets one length for all 3 axis.

**Comment by arthurwolf** [comment]
Hello !

Issues are generally only for bugs in the code : https://github.com/Smoothieware/Smoothieware/blob/edge/HowToFileIssues.md , for general questions like this, you should use the mailing lists, forums, or IRC.
I see you asked this on the deltabot ground too, so I'll answer you there, and I am closing this issue.

Cheers.
