### ISSUE TITLE
Better support for porting

### ISSUE THREAD

**Issue by beriberikix** [Smoothieware/Smoothieware#991]
It would be great if the code (and docs?) made it easier to port to different chipsets and architectures. One solution would be to move to support the new [mbed OS application architecture](https://docs.mbed.com/docs/getting-started-mbed-os/en/latest/Full_Guide/app_on_yotta/). It has a very different dependency system called [Yotta](http://yottadocs.mbed.com/) that is rather robust.

Of course, it might be easier to keep in line with the current mbed codebase and just create vendor directories and a porting guide.

**Comment by wolfmanjm** [comment]
This really has been looked at several times, and it simply is not feasible to make it that portable. We are also moving away from mbed usage too.


Thank you for the suggestion.
