### ISSUE TITLE
Problem with '?' key functionality -- output not flushed properly

### ISSUE THREAD

**Issue by johnkingsley** [Smoothieware/Smoothieware#996]
#### What were you doing?

  I use the '?' command to get the current position.
  Like this:
```
?<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.0000>
?<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.0000>
?<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.0000>
?<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.0000>
```

That works fine. As soon as the ? key is pressed, the position is printed.

However when I move to X 100, like this:
```
G0X100
```
there is a problem.  The position isn't immediately printed when I press ?.
It requires me press the ? key a second time.

Like this:
```
??<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
??<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
??<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
??<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
??<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
??<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
<Idle,MPos:100.0000,0.0000,0.0000,WPos:100.0000,0.0000,0.0000>
```

#### What did you expect to happen?

The ? functionality should work everywhere the same and not be dependant on
the current location.

#### What happened instead?

See above.

#### Branch & Commit or Version of Smoothieware

Build version: edge-785ef43, Build date: Aug  4 2016 18:01:06, MCU: LPC1768, System Clock: 100MHz

#### Hardware model you are using (Make, and version)

Chinese knockoff.

#### Host and Operating System running the Host

linux x64, connecting via USB using minicom

#### Link to and console logs

n/a
    
#### Link to running config and M503 results

n/a

**Comment by triffid** [comment]
Try cutecom, minicom may buffer stuff and not send the first ? when you
expect
